# MLP-TUNE-001 — подбор гиперпараметров Optuna

Этот notebook не создаёт 30 официальных `MLP-xxx`. Он проводит screening вокруг
принятой **MLP-024**, сохраняет каждую trial в SQLite и показывает лучшие наборы.

Порядок: **фиксированные folds → trials → таблица результатов → проверка лучших
конфигураций → отдельный официальный MLP-эксперимент**.

`test.csv` в подборе не используется. Запускайте notebook в одном kernel и после
работы завершайте его через **Kernel → Shut Down Kernel**.

## 1. Ограничиваем вычислительные потоки

Эта ячейка должна выполняться первой. `n_jobs=1` означает, что Optuna не создаёт
параллельные trials, а ограничения BLAS не позволяют одному kernel резервировать
гигабайты памяти под множество потоков.

In [1]:
import os

for variable in (
    "OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "OMP_THREAD_LIMIT",
    "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS", "BLIS_NUM_THREADS",
):
    os.environ[variable] = "1"

## 2. Импорты и источник данных

Да, здесь впервые появляется `import optuna`. Но сначала пакет должен быть частью
окружения (`requirements.txt` и `environment.yml` уже обновлены).

In [2]:
from pathlib import Path
import sys

import optuna
import pandas as pd
import torch
from IPython.display import display

torch.set_num_threads(1)

CURRENT_DIR = Path.cwd().resolve()
PROJECT_ROOT = next(
    path for path in (CURRENT_DIR, *CURRENT_DIR.parents)
    if (path / "README.md").is_file() and (path / "src").is_dir()
)
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from ml_project import DataCatalog
import ml_project.config as project_config
import ml_project.mlp_experiment as mlp_tools
import ml_project.mlp_tuning as tuning

PARENT_MODULE = "ml_project.mlp_experiments.mlp_024_dpoutmedium"
parent = mlp_tools.load_mlp_experiment(PARENT_MODULE)

catalog = DataCatalog(PROJECT_ROOT, project_config.RAW_DIR, project_config.DATASETS)
raw_train = catalog.load(project_config.TRAIN_DATASET)
prepared = parent.prepare_features(raw_train.copy(deep=True))
mlp_tools.validate_feature_data(
    prepared, raw_train, target=project_config.TARGET, key=project_config.KEY
)

build_fold_transformer = getattr(parent, "build_fold_transformer", None)
cv_splits = tuning.make_stratified_splits(
    prepared,
    target=project_config.TARGET,
    n_splits=3,
    random_state=2026,
)

print("Project:", PROJECT_ROOT)
print("Parent:", parent.EXPERIMENT.experiment_id, parent.EXPERIMENT.title)
print("Rows:", len(prepared.frame))
print("Screening folds:", len(cv_splits))

C:\ML_Progs\Runtimes\Miniforge3\envs\titanik-ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Project: D:\Projects\Titanik-ML-project
Parent: MLP-024 dpoutmedium
Rows: 891
Screening folds: 3

## 3. Пространство поиска

Optuna будет выбирать batch size, learning rate, weight decay, Dropout, глубину и
общую ширину скрытых слоёв. ReLU, положение Dropout, признаки и preprocessing
зафиксированы результатами ручных экспериментов.

Первая trial принудительно повторяет параметры MLP-024 и становится baseline на
новых screening folds. Её accuracy не обязана равняться официальным `0.8384`:
здесь используются три folds с другим seed. Все последующие trials сравниваются
именно с этой контрольной trial на тех же строках.

In [3]:
STUDY_NAME = "titanic_mlp_tuning_001"
STUDY_DIR = PROJECT_ROOT / "artifacts/optuna"
STUDY_DIR.mkdir(parents=True, exist_ok=True)
DATABASE_PATH = STUDY_DIR / f"{STUDY_NAME}.db"
STORAGE = f"sqlite:///{DATABASE_PATH.as_posix()}"

study = optuna.create_study(
    study_name=STUDY_NAME,
    storage=STORAGE,
    load_if_exists=True,
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
)

if not study.trials:
    study.enqueue_trial(tuning.BASELINE_PARAMETERS)

objective = tuning.make_objective(
    prepared,
    target=project_config.TARGET,
    key=project_config.KEY,
    base_spec=parent.EXPERIMENT,
    cv_splits=cv_splits,
    build_fold_transformer=build_fold_transformer,
)

print("Storage:", DATABASE_PATH.relative_to(PROJECT_ROOT))
print("Existing trials:", len(study.trials))
display(pd.Series(tuning.BASELINE_PARAMETERS, name="MLP-024").to_frame())

[I 2026-10-05 13:43:17,871] Using an existing study with `study_name='titanic_mlp_tuning_001'` instead of creating a new one.

Storage: artifacts\optuna\titanic_mlp_tuning_001.db
Existing trials: 1

               MLP-024
batch_size      32.000
learning_rate    0.001
weight_decay     0.000
dropout          0.200
n_layers         3.000
hidden_dim      16.000

## 4. Запуск trials

Для первого знакомства начните с 10 trials. Повторный запуск продолжит ту же
SQLite study. Когда всё понятно, измените `N_TRIALS` на 20–30.

In [8]:
N_TRIALS = 100

study.optimize(
    objective,
    n_trials=N_TRIALS,
    n_jobs=1,
    gc_after_trial=True,
    show_progress_bar=True,
)

Best trial: 19. Best value: 0.82716:   1%|          | 1/100 [00:07<11:50,  7.17s/it]

[I 2026-10-05 14:00:24,192] Trial 40 finished with value: 0.8170594837261503 and parameters: {'batch_size': 32, 'learning_rate': 0.0010963572386520648, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   2%|▏         | 2/100 [00:14<11:44,  7.19s/it]

[I 2026-10-05 14:00:31,413] Trial 41 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0015221298680985055, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   3%|▎         | 3/100 [00:18<09:02,  5.60s/it]

[I 2026-10-05 14:00:35,101] Trial 42 finished with value: 0.819304152637486 and parameters: {'batch_size': 64, 'learning_rate': 0.0028510813839912877, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   4%|▍         | 4/100 [00:23<08:49,  5.51s/it]

[I 2026-10-05 14:00:40,485] Trial 43 finished with value: 0.8159371492704826 and parameters: {'batch_size': 32, 'learning_rate': 0.0013530344725123204, 'weight_decay': 0.0, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   5%|▌         | 5/100 [00:28<08:22,  5.29s/it]

[I 2026-10-05 14:00:45,370] Trial 44 finished with value: 0.8260381593714926 and parameters: {'batch_size': 64, 'learning_rate': 0.0017283036090842327, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   6%|▌         | 6/100 [00:32<07:46,  4.96s/it]

[I 2026-10-05 14:00:49,698] Trial 45 finished with value: 0.8181818181818182 and parameters: {'batch_size': 64, 'learning_rate': 0.0022314758857362896, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   7%|▋         | 7/100 [00:38<08:11,  5.29s/it]

[I 2026-10-05 14:00:55,658] Trial 46 finished with value: 0.8226711560044894 and parameters: {'batch_size': 64, 'learning_rate': 0.0010704563363768459, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   8%|▊         | 8/100 [00:46<09:20,  6.09s/it]

[I 2026-10-05 14:01:03,471] Trial 47 finished with value: 0.8215488215488215 and parameters: {'batch_size': 16, 'learning_rate': 0.0017435009887234035, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:   9%|▉         | 9/100 [00:51<08:49,  5.81s/it]

[I 2026-10-05 14:01:08,674] Trial 48 finished with value: 0.8237934904601572 and parameters: {'batch_size': 32, 'learning_rate': 0.0017734127582660112, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  10%|█         | 10/100 [00:58<09:12,  6.14s/it]

[I 2026-10-05 14:01:15,539] Trial 49 finished with value: 0.8226711560044894 and parameters: {'batch_size': 32, 'learning_rate': 0.0015119711657222176, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  11%|█         | 11/100 [01:00<07:16,  4.91s/it]

[I 2026-10-05 14:01:17,648] Trial 50 finished with value: 0.819304152637486 and parameters: {'batch_size': 64, 'learning_rate': 0.0025458248948160866, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  12%|█▏        | 12/100 [01:07<08:11,  5.59s/it]

[I 2026-10-05 14:01:24,793] Trial 51 finished with value: 0.8249158249158249 and parameters: {'batch_size': 32, 'learning_rate': 0.0010913588901736472, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  13%|█▎        | 13/100 [01:11<07:24,  5.11s/it]

[I 2026-10-05 14:01:28,808] Trial 52 finished with value: 0.8226711560044894 and parameters: {'batch_size': 64, 'learning_rate': 0.0029513861513313297, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  14%|█▍        | 14/100 [01:18<07:57,  5.55s/it]

[I 2026-10-05 14:01:35,387] Trial 53 finished with value: 0.8170594837261503 and parameters: {'batch_size': 32, 'learning_rate': 0.002067891245951292, 'weight_decay': 0.0, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  15%|█▌        | 15/100 [01:23<07:30,  5.30s/it]

[I 2026-10-05 14:01:40,092] Trial 54 finished with value: 0.8215488215488215 and parameters: {'batch_size': 64, 'learning_rate': 0.001591708424288705, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  16%|█▌        | 16/100 [01:26<06:41,  4.78s/it]

[I 2026-10-05 14:01:43,672] Trial 55 finished with value: 0.8204264870931538 and parameters: {'batch_size': 32, 'learning_rate': 0.0016608645718495527, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  17%|█▋        | 17/100 [01:29<05:44,  4.15s/it]

[I 2026-10-05 14:01:46,343] Trial 56 finished with value: 0.8148148148148148 and parameters: {'batch_size': 32, 'learning_rate': 0.002253346524795198, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  18%|█▊        | 18/100 [01:34<05:55,  4.33s/it]

[I 2026-10-05 14:01:51,103] Trial 57 finished with value: 0.8260381593714928 and parameters: {'batch_size': 32, 'learning_rate': 0.0029670493235096334, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  19%|█▉        | 19/100 [01:40<06:37,  4.91s/it]

[I 2026-10-05 14:01:57,361] Trial 58 finished with value: 0.8271604938271606 and parameters: {'batch_size': 32, 'learning_rate': 0.0023159416442236815, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  20%|██        | 20/100 [01:49<08:12,  6.15s/it]

[I 2026-10-05 14:02:06,411] Trial 59 finished with value: 0.8103254769921437 and parameters: {'batch_size': 16, 'learning_rate': 0.002188833744889398, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  21%|██        | 21/100 [01:54<07:45,  5.90s/it]

[I 2026-10-05 14:02:11,706] Trial 60 finished with value: 0.8170594837261503 and parameters: {'batch_size': 32, 'learning_rate': 0.0025553712413436077, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  22%|██▏       | 22/100 [02:00<07:28,  5.75s/it]

[I 2026-10-05 14:02:17,131] Trial 61 finished with value: 0.8215488215488215 and parameters: {'batch_size': 32, 'learning_rate': 0.0026393103648501186, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  23%|██▎       | 23/100 [02:05<07:14,  5.64s/it]

[I 2026-10-05 14:02:22,522] Trial 62 finished with value: 0.8226711560044894 and parameters: {'batch_size': 64, 'learning_rate': 0.000895848609167078, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  24%|██▍       | 24/100 [02:10<06:53,  5.44s/it]

[I 2026-10-05 14:02:27,484] Trial 63 finished with value: 0.8215488215488215 and parameters: {'batch_size': 64, 'learning_rate': 0.001358571049604824, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  25%|██▌       | 25/100 [02:14<06:15,  5.00s/it]

[I 2026-10-05 14:02:31,472] Trial 64 finished with value: 0.8271604938271605 and parameters: {'batch_size': 32, 'learning_rate': 0.002934132167973449, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  26%|██▌       | 26/100 [02:20<06:25,  5.21s/it]

[I 2026-10-05 14:02:37,175] Trial 65 finished with value: 0.8249158249158249 and parameters: {'batch_size': 32, 'learning_rate': 0.002875310816801406, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  27%|██▋       | 27/100 [02:23<05:33,  4.57s/it]

[I 2026-10-05 14:02:40,247] Trial 66 finished with value: 0.8136924803591471 and parameters: {'batch_size': 32, 'learning_rate': 0.0026475473288281376, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 16}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  28%|██▊       | 28/100 [02:28<05:41,  4.74s/it]

[I 2026-10-05 14:02:45,371] Trial 67 finished with value: 0.8260381593714928 and parameters: {'batch_size': 32, 'learning_rate': 0.002089524083913421, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 19. Best value: 0.82716:  29%|██▉       | 29/100 [02:35<06:26,  5.45s/it]

[I 2026-10-05 14:02:52,481] Trial 68 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.001285993859509224, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 19 with value: 0.8271604938271606.

Best trial: 69. Best value: 0.829405:  30%|███       | 30/100 [02:41<06:30,  5.57s/it]

[I 2026-10-05 14:02:58,340] Trial 69 finished with value: 0.8294051627384961 and parameters: {'batch_size': 32, 'learning_rate': 0.0019554513736881884, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  31%|███       | 31/100 [02:48<06:51,  5.96s/it]

[I 2026-10-05 14:03:05,218] Trial 70 finished with value: 0.8159371492704826 and parameters: {'batch_size': 16, 'learning_rate': 0.002354120778210295, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  32%|███▏      | 32/100 [02:54<07:00,  6.19s/it]

[I 2026-10-05 14:03:11,933] Trial 71 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0020067512316711577, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  33%|███▎      | 33/100 [02:57<05:34,  4.99s/it]

[I 2026-10-05 14:03:14,114] Trial 72 finished with value: 0.8226711560044894 and parameters: {'batch_size': 32, 'learning_rate': 0.002974298057820341, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  34%|███▍      | 34/100 [03:02<05:47,  5.26s/it]

[I 2026-10-05 14:03:20,021] Trial 73 finished with value: 0.8103254769921436 and parameters: {'batch_size': 32, 'learning_rate': 0.001979802528860119, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  35%|███▌      | 35/100 [03:09<06:05,  5.62s/it]

[I 2026-10-05 14:03:26,482] Trial 74 finished with value: 0.8271604938271606 and parameters: {'batch_size': 32, 'learning_rate': 0.001526931267134366, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  36%|███▌      | 36/100 [03:14<05:42,  5.35s/it]

[I 2026-10-05 14:03:31,207] Trial 75 finished with value: 0.8226711560044894 and parameters: {'batch_size': 32, 'learning_rate': 0.0013404673279287561, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  37%|███▋      | 37/100 [03:19<05:38,  5.37s/it]

[I 2026-10-05 14:03:36,605] Trial 76 finished with value: 0.8249158249158249 and parameters: {'batch_size': 32, 'learning_rate': 0.001565170605101538, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  38%|███▊      | 38/100 [03:25<05:38,  5.46s/it]

[I 2026-10-05 14:03:42,281] Trial 77 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.0018123617931449596, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  39%|███▉      | 39/100 [03:31<05:45,  5.67s/it]

[I 2026-10-05 14:03:48,429] Trial 78 finished with value: 0.8170594837261503 and parameters: {'batch_size': 32, 'learning_rate': 0.0024919635151572227, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  40%|████      | 40/100 [03:36<05:28,  5.47s/it]

[I 2026-10-05 14:03:53,435] Trial 79 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.0015913257038827665, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  41%|████      | 41/100 [03:41<05:23,  5.48s/it]

[I 2026-10-05 14:03:58,945] Trial 80 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0012258799117244427, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  42%|████▏     | 42/100 [03:48<05:40,  5.88s/it]

[I 2026-10-05 14:04:05,743] Trial 81 finished with value: 0.8193041526374859 and parameters: {'batch_size': 32, 'learning_rate': 0.0016098823372222128, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  43%|████▎     | 43/100 [03:52<04:58,  5.24s/it]

[I 2026-10-05 14:04:09,489] Trial 82 finished with value: 0.8170594837261503 and parameters: {'batch_size': 32, 'learning_rate': 0.0017478507261917307, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  44%|████▍     | 44/100 [04:00<05:34,  5.97s/it]

[I 2026-10-05 14:04:17,155] Trial 83 finished with value: 0.8215488215488215 and parameters: {'batch_size': 32, 'learning_rate': 0.0012713335908762526, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  45%|████▌     | 45/100 [04:07<05:43,  6.24s/it]

[I 2026-10-05 14:04:24,050] Trial 84 finished with value: 0.8181818181818182 and parameters: {'batch_size': 32, 'learning_rate': 0.0016446687068852786, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 69. Best value: 0.829405:  46%|████▌     | 46/100 [04:11<05:05,  5.66s/it]

[I 2026-10-05 14:04:28,335] Trial 85 finished with value: 0.8181818181818182 and parameters: {'batch_size': 32, 'learning_rate': 0.002451545378922688, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 69 with value: 0.8294051627384961.

Best trial: 86. Best value: 0.832772:  47%|████▋     | 47/100 [04:18<05:23,  6.10s/it]

[I 2026-10-05 14:04:35,469] Trial 86 finished with value: 0.8327721661054994 and parameters: {'batch_size': 32, 'learning_rate': 0.0017503534730658975, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  48%|████▊     | 48/100 [04:23<05:01,  5.79s/it]

[I 2026-10-05 14:04:40,547] Trial 87 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0026798237938837526, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  49%|████▉     | 49/100 [04:27<04:33,  5.35s/it]

[I 2026-10-05 14:04:44,876] Trial 88 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0020519900066651667, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  50%|█████     | 50/100 [04:35<04:56,  5.92s/it]

[I 2026-10-05 14:04:52,127] Trial 89 finished with value: 0.8215488215488215 and parameters: {'batch_size': 32, 'learning_rate': 0.0015963018495810959, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  51%|█████     | 51/100 [04:40<04:41,  5.74s/it]

[I 2026-10-05 14:04:57,439] Trial 90 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.0016841147579690862, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  52%|█████▏    | 52/100 [04:44<04:13,  5.28s/it]

[I 2026-10-05 14:05:01,630] Trial 91 finished with value: 0.8181818181818182 and parameters: {'batch_size': 32, 'learning_rate': 0.002967357300470165, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  53%|█████▎    | 53/100 [04:49<04:04,  5.20s/it]

[I 2026-10-05 14:05:06,662] Trial 92 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.00235277907368589, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  54%|█████▍    | 54/100 [04:52<03:31,  4.59s/it]

[I 2026-10-05 14:05:09,828] Trial 93 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.00284499784011754, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  55%|█████▌    | 55/100 [04:56<03:19,  4.43s/it]

[I 2026-10-05 14:05:13,867] Trial 94 finished with value: 0.8215488215488215 and parameters: {'batch_size': 32, 'learning_rate': 0.002224187613332908, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  56%|█████▌    | 56/100 [05:02<03:34,  4.87s/it]

[I 2026-10-05 14:05:19,779] Trial 95 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0012454306242686455, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  57%|█████▋    | 57/100 [05:06<03:18,  4.61s/it]

[I 2026-10-05 14:05:23,777] Trial 96 finished with value: 0.8237934904601572 and parameters: {'batch_size': 32, 'learning_rate': 0.0024992574758004537, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  58%|█████▊    | 58/100 [05:12<03:27,  4.93s/it]

[I 2026-10-05 14:05:29,455] Trial 97 finished with value: 0.8170594837261503 and parameters: {'batch_size': 32, 'learning_rate': 0.0022121754659261, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  59%|█████▉    | 59/100 [05:19<03:45,  5.49s/it]

[I 2026-10-05 14:05:36,267] Trial 98 finished with value: 0.8226711560044894 and parameters: {'batch_size': 32, 'learning_rate': 0.001394390288057211, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  60%|██████    | 60/100 [05:26<04:00,  6.02s/it]

[I 2026-10-05 14:05:43,499] Trial 99 finished with value: 0.8125701459034792 and parameters: {'batch_size': 32, 'learning_rate': 0.0015048827627267961, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  61%|██████    | 61/100 [05:33<04:05,  6.31s/it]

[I 2026-10-05 14:05:50,428] Trial 100 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.002306115249617664, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  62%|██████▏   | 62/100 [05:36<03:25,  5.42s/it]

[I 2026-10-05 14:05:53,819] Trial 101 finished with value: 0.818181818181818 and parameters: {'batch_size': 32, 'learning_rate': 0.002345098479278479, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  63%|██████▎   | 63/100 [05:43<03:32,  5.73s/it]

[I 2026-10-05 14:06:00,273] Trial 102 finished with value: 0.8215488215488217 and parameters: {'batch_size': 16, 'learning_rate': 0.002237109908706419, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  64%|██████▍   | 64/100 [05:48<03:16,  5.45s/it]

[I 2026-10-05 14:06:05,075] Trial 103 finished with value: 0.8294051627384961 and parameters: {'batch_size': 64, 'learning_rate': 0.0018534485544014017, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  65%|██████▌   | 65/100 [05:53<03:09,  5.41s/it]

[I 2026-10-05 14:06:10,402] Trial 104 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.002120250678611318, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  66%|██████▌   | 66/100 [05:58<02:56,  5.18s/it]

[I 2026-10-05 14:06:15,054] Trial 105 finished with value: 0.8237934904601572 and parameters: {'batch_size': 64, 'learning_rate': 0.002084034546063282, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  67%|██████▋   | 67/100 [06:03<02:49,  5.14s/it]

[I 2026-10-05 14:06:20,094] Trial 106 finished with value: 0.8294051627384961 and parameters: {'batch_size': 64, 'learning_rate': 0.0017198429779176523, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  68%|██████▊   | 68/100 [06:05<02:15,  4.22s/it]

[I 2026-10-05 14:06:22,176] Trial 107 finished with value: 0.818181818181818 and parameters: {'batch_size': 64, 'learning_rate': 0.0016614700436456144, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  69%|██████▉   | 69/100 [06:10<02:20,  4.52s/it]

[I 2026-10-05 14:06:27,406] Trial 108 finished with value: 0.8215488215488215 and parameters: {'batch_size': 64, 'learning_rate': 0.0014512939231914447, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  70%|███████   | 70/100 [06:15<02:22,  4.74s/it]

[I 2026-10-05 14:06:32,643] Trial 109 finished with value: 0.8260381593714928 and parameters: {'batch_size': 64, 'learning_rate': 0.0017930785972338525, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  71%|███████   | 71/100 [06:19<02:08,  4.43s/it]

[I 2026-10-05 14:06:36,347] Trial 110 finished with value: 0.8159371492704826 and parameters: {'batch_size': 32, 'learning_rate': 0.0014549266647099902, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  72%|███████▏  | 72/100 [06:24<02:09,  4.63s/it]

[I 2026-10-05 14:06:41,457] Trial 111 finished with value: 0.829405162738496 and parameters: {'batch_size': 64, 'learning_rate': 0.001902477346789912, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  73%|███████▎  | 73/100 [06:28<02:03,  4.59s/it]

[I 2026-10-05 14:06:45,952] Trial 112 finished with value: 0.8181818181818182 and parameters: {'batch_size': 64, 'learning_rate': 0.0023405938960238157, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  74%|███████▍  | 74/100 [06:34<02:05,  4.83s/it]

[I 2026-10-05 14:06:51,358] Trial 113 finished with value: 0.8237934904601572 and parameters: {'batch_size': 64, 'learning_rate': 0.0012504918897458946, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  75%|███████▌  | 75/100 [06:41<02:16,  5.48s/it]

[I 2026-10-05 14:06:58,329] Trial 114 finished with value: 0.8181818181818182 and parameters: {'batch_size': 32, 'learning_rate': 0.001840726757291404, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  76%|███████▌  | 76/100 [06:45<02:00,  5.02s/it]

[I 2026-10-05 14:07:02,276] Trial 115 finished with value: 0.8181818181818182 and parameters: {'batch_size': 32, 'learning_rate': 0.0015373401807724295, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 16}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  77%|███████▋  | 77/100 [06:50<01:58,  5.14s/it]

[I 2026-10-05 14:07:07,696] Trial 116 finished with value: 0.8249158249158249 and parameters: {'batch_size': 32, 'learning_rate': 0.0029059953967064045, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  78%|███████▊  | 78/100 [06:52<01:33,  4.26s/it]

[I 2026-10-05 14:07:09,926] Trial 117 finished with value: 0.8271604938271605 and parameters: {'batch_size': 64, 'learning_rate': 0.0017554817081351232, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  79%|███████▉  | 79/100 [06:55<01:17,  3.68s/it]

[I 2026-10-05 14:07:12,231] Trial 118 finished with value: 0.8249158249158248 and parameters: {'batch_size': 64, 'learning_rate': 0.0016939666649639043, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  80%|████████  | 80/100 [06:57<01:06,  3.31s/it]

[I 2026-10-05 14:07:14,659] Trial 119 finished with value: 0.8237934904601572 and parameters: {'batch_size': 64, 'learning_rate': 0.0016864749164993253, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  81%|████████  | 81/100 [07:05<01:30,  4.74s/it]

[I 2026-10-05 14:07:22,756] Trial 120 finished with value: 0.8148148148148149 and parameters: {'batch_size': 32, 'learning_rate': 0.0018592563904410594, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  82%|████████▏ | 82/100 [07:08<01:16,  4.22s/it]

[I 2026-10-05 14:07:25,770] Trial 121 finished with value: 0.819304152637486 and parameters: {'batch_size': 32, 'learning_rate': 0.0015201156268838402, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  83%|████████▎ | 83/100 [07:11<01:02,  3.65s/it]

[I 2026-10-05 14:07:28,088] Trial 122 finished with value: 0.8136924803591471 and parameters: {'batch_size': 64, 'learning_rate': 0.0018952046198358469, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  84%|████████▍ | 84/100 [07:16<01:07,  4.20s/it]

[I 2026-10-05 14:07:33,591] Trial 123 finished with value: 0.8148148148148149 and parameters: {'batch_size': 32, 'learning_rate': 0.0027319720905859927, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  85%|████████▌ | 85/100 [07:21<01:08,  4.56s/it]

[I 2026-10-05 14:07:38,973] Trial 124 finished with value: 0.8215488215488215 and parameters: {'batch_size': 64, 'learning_rate': 0.001926324340734597, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  86%|████████▌ | 86/100 [07:24<00:54,  3.92s/it]

[I 2026-10-05 14:07:41,417] Trial 125 finished with value: 0.8226711560044894 and parameters: {'batch_size': 64, 'learning_rate': 0.002076023627365532, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  87%|████████▋ | 87/100 [07:27<00:46,  3.61s/it]

[I 2026-10-05 14:07:44,301] Trial 126 finished with value: 0.8215488215488215 and parameters: {'batch_size': 64, 'learning_rate': 0.0013912227046387633, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 24}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  88%|████████▊ | 88/100 [07:29<00:39,  3.29s/it]

[I 2026-10-05 14:07:46,840] Trial 127 finished with value: 0.8226711560044894 and parameters: {'batch_size': 64, 'learning_rate': 0.001637048269965692, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  89%|████████▉ | 89/100 [07:35<00:43,  3.92s/it]

[I 2026-10-05 14:07:52,219] Trial 128 finished with value: 0.8226711560044894 and parameters: {'batch_size': 64, 'learning_rate': 0.001789540171914523, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  90%|█████████ | 90/100 [07:37<00:34,  3.42s/it]

[I 2026-10-05 14:07:54,482] Trial 129 finished with value: 0.8271604938271606 and parameters: {'batch_size': 64, 'learning_rate': 0.00180140239228324, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  91%|█████████ | 91/100 [07:39<00:27,  3.00s/it]

[I 2026-10-05 14:07:56,515] Trial 130 finished with value: 0.8170594837261503 and parameters: {'batch_size': 64, 'learning_rate': 0.0019147944018622748, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  92%|█████████▏| 92/100 [07:41<00:21,  2.75s/it]

[I 2026-10-05 14:07:58,661] Trial 131 finished with value: 0.8204264870931537 and parameters: {'batch_size': 64, 'learning_rate': 0.0018378283353644533, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  93%|█████████▎| 93/100 [07:48<00:27,  3.91s/it]

[I 2026-10-05 14:08:05,297] Trial 132 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.0019439452201307171, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  94%|█████████▍| 94/100 [07:50<00:20,  3.35s/it]

[I 2026-10-05 14:08:07,321] Trial 133 finished with value: 0.8204264870931538 and parameters: {'batch_size': 64, 'learning_rate': 0.001909782993545148, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  95%|█████████▌| 95/100 [07:54<00:18,  3.71s/it]

[I 2026-10-05 14:08:11,887] Trial 134 finished with value: 0.8226711560044894 and parameters: {'batch_size': 32, 'learning_rate': 0.0028619960664148982, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  96%|█████████▌| 96/100 [08:02<00:19,  4.86s/it]

[I 2026-10-05 14:08:19,432] Trial 135 finished with value: 0.8204264870931538 and parameters: {'batch_size': 32, 'learning_rate': 0.001550846439327267, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  97%|█████████▋| 97/100 [08:07<00:14,  4.96s/it]

[I 2026-10-05 14:08:24,618] Trial 136 finished with value: 0.8204264870931537 and parameters: {'batch_size': 32, 'learning_rate': 0.0018989827851786394, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  98%|█████████▊| 98/100 [08:09<00:08,  4.18s/it]

[I 2026-10-05 14:08:26,975] Trial 137 finished with value: 0.8204264870931537 and parameters: {'batch_size': 64, 'learning_rate': 0.001299081815862803, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772:  99%|█████████▉| 99/100 [08:11<00:03,  3.53s/it]

[I 2026-10-05 14:08:28,982] Trial 138 finished with value: 0.8249158249158249 and parameters: {'batch_size': 64, 'learning_rate': 0.0020647919144194254, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 32}. Best is trial 86 with value: 0.8327721661054994.

Best trial: 86. Best value: 0.832772: 100%|██████████| 100/100 [08:17<00:00,  4.98s/it]

[I 2026-10-05 14:08:34,553] Trial 139 finished with value: 0.8181818181818182 and parameters: {'batch_size': 64, 'learning_rate': 0.0015940053829212974, 'weight_decay': 0.001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 86 with value: 0.8327721661054994.

## 5. Результаты

`value` — средняя accuracy на трёх одинаковых screening folds. Эта таблица нужна
для отбора кандидатов, а не для объявления нового чемпиона.

In [9]:
trials = study.trials_dataframe()
trials.to_csv(STUDY_DIR / f"{STUDY_NAME}_trials.csv", index=False)

columns = [
    "number", "value", "state",
    "params_batch_size", "params_learning_rate", "params_weight_decay",
    "params_dropout", "params_n_layers", "params_hidden_dim",
    "user_attrs_accuracy_std", "user_attrs_log_loss_mean",
]
available = [column for column in columns if column in trials]
display(
    trials.loc[trials["state"].eq("COMPLETE"), available]
    .sort_values("value", ascending=False)
    .head(10)
)

print("Best screening accuracy:", study.best_value)
print("Best parameters:", study.best_params)

,number,value,state,params_batch_size,params_learning_rate,params_weight_decay,params_dropout,params_n_layers,params_hidden_dim,user_attrs_accuracy_std,user_attrs_log_loss_mean
86,86,0.832772,COMPLETE,32,0.001750,1.000000e-04,0.30,4,8,0.023888,0.454552
106,106,0.829405,COMPLETE,64,0.001720,1.000000e-06,0.10,4,8,0.030551,0.442854
69,69,0.829405,COMPLETE,32,0.001955,1.000000e-06,0.10,4,8,0.018544,0.443216
103,103,0.829405,COMPLETE,64,0.001853,1.000000e-06,0.10,4,8,0.023888,0.438748
111,111,0.829405,COMPLETE,64,0.001902,1.000000e-06,0.15,4,8,0.031824,0.435031
58,58,0.827160,COMPLETE,32,0.002316,1.000000e-06,0.25,4,8,0.022419,0.467705
129,129,0.827160,COMPLETE,64,0.001801,1.000000e-06,0.25,4,32,0.028036,0.428937
74,74,0.827160,COMPLETE,32,0.001527,1.000000e-07,0.10,4,8,0.023649,0.445297
19,19,0.827160,COMPLETE,32,0.001468,1.000000e-07,0.15,4,8,0.019146,0.459858
64,64,0.827160,COMPLETE,32,0.002934,1.000000e-07,0.10,4,8,0.024819,0.437724

Best screening accuracy: 0.8327721661054994
Best parameters: {'batch_size': 32, 'learning_rate': 0.0017503534730658975, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}

## 6. Что делать с победителем

1. Не помечать trial как `adopt`.
2. Взять 3–5 лучших конфигураций и проверить их на официальных пяти folds и
   нескольких seed.
3. Создать `new-MLPexperiment.cmd` на основе MLP-024.
4. Перенести только выбранные параметры и архитектуру.
5. Выполнить обычный notebook, получить paired-сравнение и только затем принять
   или отклонить кандидата.

SQLite и CSV находятся в `artifacts/optuna/`; повторный запуск продолжает study.