# MLP-TUNE-002 — архитектура и функции активации

Это отдельное исследование после 140 trials `MLP-TUNE-001`. Оно не изменяет
первую SQLite study и не создаёт официальные `MLP-xxx` эксперименты.

Optuna подбирает архитектуру, функцию активации и параметры обучения. Первая
trial воспроизводит лучший screening-вариант №86 с `ReLU`. После screening
несколько кандидатов обязательно проверяются на пяти официальных folds.

`test.csv` здесь не используется. После работы завершите kernel через
**Kernel → Shut Down Kernel**, чтобы освободить память.

## 1. Ограничиваем потоки

Выполните эту ячейку первой. Trials идут последовательно, а библиотеки линейной
алгебры не создают лишние рабочие потоки.

In [1]:
import os

for variable in (
    "OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "OMP_THREAD_LIMIT",
    "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS", "BLIS_NUM_THREADS",
):
    os.environ[variable] = "1"

## 2. Данные и фиксированные screening folds

Используются те же признаки и fold-safe преобразования, что у принятой MLP-024.
Все trials видят одинаковые три folds с seed 2026, поэтому их можно сравнивать
между собой.

In [2]:
from dataclasses import replace
from pathlib import Path
import sys

import optuna
import pandas as pd
import torch
from IPython.display import display

torch.set_num_threads(1)

CURRENT_DIR = Path.cwd().resolve()
PROJECT_ROOT = next(
    path for path in (CURRENT_DIR, *CURRENT_DIR.parents)
    if (path / "README.md").is_file() and (path / "src").is_dir()
)
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from ml_project import DataCatalog
import ml_project.config as project_config
import ml_project.mlp_experiment as mlp_tools
import ml_project.mlp_tuning as tuning

PARENT_MODULE = "ml_project.mlp_experiments.mlp_024_dpoutmedium"
parent = mlp_tools.load_mlp_experiment(PARENT_MODULE)

catalog = DataCatalog(PROJECT_ROOT, project_config.RAW_DIR, project_config.DATASETS)
raw_train = catalog.load(project_config.TRAIN_DATASET)
prepared = parent.prepare_features(raw_train.copy(deep=True))
mlp_tools.validate_feature_data(
    prepared, raw_train, target=project_config.TARGET, key=project_config.KEY
)

build_fold_transformer = getattr(parent, "build_fold_transformer", None)
screening_splits = tuning.make_stratified_splits(
    prepared,
    target=project_config.TARGET,
    n_splits=3,
    random_state=2026,
)

print("Project:", PROJECT_ROOT)
print("Parent:", parent.EXPERIMENT.experiment_id, parent.EXPERIMENT.title)
print("Rows:", len(prepared.frame))
print("Screening folds:", len(screening_splits))

C:\ML_Progs\Runtimes\Miniforge3\envs\titanik-ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Project: D:\Projects\Titanik-ML-project
Parent: MLP-024 dpoutmedium
Rows: 891
Screening folds: 3

## 3. Что выбирает Optuna

Каждая сеть использует одну функцию активации во всех скрытых слоях:
`ReLU`, `LeakyReLU`, `GELU`, `SiLU` или `SquaredReLU`. Для `LeakyReLU`
дополнительно выбирается `negative_slope`.

Также меняются:

- `batch_size`: 32 или 64;
- `learning_rate`: от 0.0012 до 0.0025;
- `weight_decay`: от 1e-7 до 1e-4;
- `dropout`: от 0.05 до 0.30;
- число скрытых слоёв: от 3 до 5;
- общая ширина скрытых слоёв: 4, 8, 12 или 16.

Dropout остаётся после последнего скрытого слоя. BatchNorm не добавляется.

In [3]:
STUDY_NAME = "titanic_mlp_tuning_002"
STUDY_DIR = PROJECT_ROOT / "artifacts/optuna"
STUDY_DIR.mkdir(parents=True, exist_ok=True)
DATABASE_PATH = STUDY_DIR / f"{STUDY_NAME}.db"
STORAGE = f"sqlite:///{DATABASE_PATH.as_posix()}"

study = optuna.create_study(
    study_name=STUDY_NAME,
    storage=STORAGE,
    load_if_exists=True,
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=43),
)

if not study.trials:
    study.enqueue_trial(tuning.PHASE2_BASELINE_PARAMETERS)

objective = tuning.make_phase2_objective(
    prepared,
    target=project_config.TARGET,
    key=project_config.KEY,
    base_spec=parent.EXPERIMENT,
    cv_splits=screening_splits,
    build_fold_transformer=build_fold_transformer,
)

print("Storage:", DATABASE_PATH.relative_to(PROJECT_ROOT))
print("Existing trials:", len(study.trials))
display(pd.Series(tuning.PHASE2_BASELINE_PARAMETERS, name="trial 86 + ReLU").to_frame())

[I 2026-10-05 14:35:18,679] A new study created in RDB with name: titanic_mlp_tuning_002

Storage: artifacts\optuna\titanic_mlp_tuning_002.db
Existing trials: 1

              trial 86 + ReLU
batch_size                 32
learning_rate         0.00175
weight_decay           0.0001
dropout                   0.3
n_layers                    4
hidden_dim                  8
activation               relu

## 4. Запускаем небольшими этапами

Начните с 20 trials. Повторный запуск этой ячейки добавит ещё 20 в ту же study.
После 60–80 trials проверьте, продолжает ли улучшаться максимум и какие активации
встречаются среди лучших результатов.

In [7]:
N_TRIALS = 500

study.optimize(
    objective,
    n_trials=N_TRIALS,
    n_jobs=1,
    gc_after_trial=True,
    show_progress_bar=True,
)

Best trial: 0. Best value: 0.832772:   0%|          | 1/500 [00:05<43:50,  5.27s/it]

[I 2026-10-05 14:53:11,870] Trial 130 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0015053842021964775, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   0%|          | 2/500 [00:11<49:36,  5.98s/it]

[I 2026-10-05 14:53:18,335] Trial 131 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013526328397794084, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   1%|          | 3/500 [00:17<50:02,  6.04s/it]

[I 2026-10-05 14:53:24,449] Trial 132 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013398859681689806, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   1%|          | 4/500 [00:23<48:09,  5.83s/it]

[I 2026-10-05 14:53:29,951] Trial 133 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001899101936569377, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   1%|          | 5/500 [00:30<50:34,  6.13s/it]

[I 2026-10-05 14:53:36,610] Trial 134 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012513522337991153, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   1%|          | 6/500 [00:35<49:47,  6.05s/it]

[I 2026-10-05 14:53:42,503] Trial 135 finished with value: 0.8260381593714926 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0015334127828945505, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   1%|▏         | 7/500 [00:41<48:34,  5.91s/it]

[I 2026-10-05 14:53:48,131] Trial 136 finished with value: 0.829405162738496 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017903356516822914, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   2%|▏         | 8/500 [00:48<50:18,  6.14s/it]

[I 2026-10-05 14:53:54,730] Trial 137 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012851267277327661, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   2%|▏         | 9/500 [00:55<52:10,  6.38s/it]

[I 2026-10-05 14:54:01,635] Trial 138 finished with value: 0.8294051627384961 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001239073076233945, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   2%|▏         | 10/500 [01:01<52:26,  6.42s/it]

[I 2026-10-05 14:54:08,142] Trial 139 finished with value: 0.8193041526374859 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012438427047008758, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   2%|▏         | 11/500 [01:05<46:59,  5.77s/it]

[I 2026-10-05 14:54:12,455] Trial 140 finished with value: 0.8024691358024691 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001747664887559684, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   2%|▏         | 12/500 [01:14<54:37,  6.72s/it]

[I 2026-10-05 14:54:21,338] Trial 141 finished with value: 0.8103254769921436 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012092431603547861, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   3%|▎         | 13/500 [01:20<52:51,  6.51s/it]

[I 2026-10-05 14:54:27,390] Trial 142 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001788736714706458, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   3%|▎         | 14/500 [01:24<46:42,  5.77s/it]

[I 2026-10-05 14:54:31,424] Trial 143 finished with value: 0.8215488215488217 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001870509025876575, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   3%|▎         | 15/500 [01:32<52:03,  6.44s/it]

[I 2026-10-05 14:54:39,416] Trial 144 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012903782124005635, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 5, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   3%|▎         | 16/500 [01:41<58:01,  7.19s/it]

[I 2026-10-05 14:54:48,372] Trial 145 finished with value: 0.8092031425364757 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012370943126351116, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   3%|▎         | 17/500 [01:47<54:02,  6.71s/it]

[I 2026-10-05 14:54:53,969] Trial 146 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013158189676452654, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   4%|▎         | 18/500 [01:54<55:39,  6.93s/it]

[I 2026-10-05 14:55:01,403] Trial 147 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012047072072404205, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   4%|▍         | 19/500 [01:59<51:16,  6.40s/it]

[I 2026-10-05 14:55:06,555] Trial 148 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001988859488711681, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   4%|▍         | 20/500 [02:04<46:19,  5.79s/it]

[I 2026-10-05 14:55:10,928] Trial 149 finished with value: 0.8114478114478114 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012567899984983148, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   4%|▍         | 21/500 [02:11<49:03,  6.15s/it]

[I 2026-10-05 14:55:17,907] Trial 150 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001294728670188172, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   4%|▍         | 22/500 [02:16<46:30,  5.84s/it]

[I 2026-10-05 14:55:23,028] Trial 151 finished with value: 0.8204264870931537 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012930940928857647, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   5%|▍         | 23/500 [02:21<45:23,  5.71s/it]

[I 2026-10-05 14:55:28,430] Trial 152 finished with value: 0.7564534231200898 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0012927349180147038, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   5%|▍         | 23/500 [02:32<45:23,  5.71s/it]

[I 2026-10-05 14:55:38,574] Trial 153 finished with value: 0.8159371492704827 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017439883010871733, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   5%|▌         | 25/500 [02:38<54:28,  6.88s/it]

[I 2026-10-05 14:55:45,073] Trial 154 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.001315852627331378, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   5%|▌         | 26/500 [02:48<1:01:34,  7.79s/it]

[I 2026-10-05 14:55:55,024] Trial 155 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012205590117010732, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   5%|▌         | 27/500 [02:54<56:39,  7.19s/it]

[I 2026-10-05 14:56:00,802] Trial 156 finished with value: 0.8148148148148149 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012387371590351494, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   6%|▌         | 28/500 [02:57<46:30,  5.91s/it]

[I 2026-10-05 14:56:03,739] Trial 157 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013942438562018847, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   6%|▌         | 29/500 [03:03<48:09,  6.14s/it]

[I 2026-10-05 14:56:10,398] Trial 158 finished with value: 0.8204264870931537 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012494921052296703, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   6%|▌         | 30/500 [03:10<48:15,  6.16s/it]

[I 2026-10-05 14:56:16,613] Trial 159 finished with value: 0.8294051627384961 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018433180016000248, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   6%|▌         | 31/500 [03:16<48:19,  6.18s/it]

[I 2026-10-05 14:56:22,843] Trial 160 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0019223234284059744, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   6%|▋         | 32/500 [03:22<48:18,  6.19s/it]

[I 2026-10-05 14:56:29,065] Trial 161 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001811100591885877, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   7%|▋         | 33/500 [03:29<50:42,  6.51s/it]

[I 2026-10-05 14:56:36,320] Trial 162 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012074885707817947, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   7%|▋         | 34/500 [03:37<52:53,  6.81s/it]

[I 2026-10-05 14:56:43,827] Trial 163 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001219124995420848, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   7%|▋         | 35/500 [03:43<51:30,  6.65s/it]

[I 2026-10-05 14:56:50,093] Trial 164 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018368894853455497, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   7%|▋         | 36/500 [03:48<47:20,  6.12s/it]

[I 2026-10-05 14:56:54,986] Trial 165 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018296707995120653, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   7%|▋         | 37/500 [03:52<42:16,  5.48s/it]

[I 2026-10-05 14:56:58,964] Trial 166 finished with value: 0.8170594837261503 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0017745332114911375, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   8%|▊         | 38/500 [03:55<37:41,  4.90s/it]

[I 2026-10-05 14:57:02,505] Trial 167 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012800376687181613, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   8%|▊         | 39/500 [04:02<41:02,  5.34s/it]

[I 2026-10-05 14:57:08,882] Trial 168 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017458711781114982, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   8%|▊         | 40/500 [04:11<49:21,  6.44s/it]

[I 2026-10-05 14:57:17,881] Trial 169 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013462753895776343, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   8%|▊         | 41/500 [04:17<48:21,  6.32s/it]

[I 2026-10-05 14:57:23,915] Trial 170 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001992910085622583, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   8%|▊         | 42/500 [04:24<49:40,  6.51s/it]

[I 2026-10-05 14:57:30,867] Trial 171 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001261242628334445, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   9%|▊         | 43/500 [04:30<49:32,  6.51s/it]

[I 2026-10-05 14:57:37,370] Trial 172 finished with value: 0.8249158249158249 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0012716238327789811, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   9%|▉         | 44/500 [04:35<45:32,  5.99s/it]

[I 2026-10-05 14:57:42,169] Trial 173 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017341834706526623, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   9%|▉         | 45/500 [04:41<46:16,  6.10s/it]

[I 2026-10-05 14:57:48,526] Trial 174 finished with value: 0.8294051627384961 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013051094080706494, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   9%|▉         | 46/500 [04:45<40:22,  5.34s/it]

[I 2026-10-05 14:57:52,073] Trial 175 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001333598407314463, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:   9%|▉         | 47/500 [04:52<43:57,  5.82s/it]

[I 2026-10-05 14:57:59,028] Trial 176 finished with value: 0.8148148148148149 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018503232837690574, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  10%|▉         | 48/500 [04:58<45:23,  6.03s/it]

[I 2026-10-05 14:58:05,524] Trial 177 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.00131097164131853, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  10%|▉         | 49/500 [05:05<45:56,  6.11s/it]

[I 2026-10-05 14:58:11,844] Trial 178 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012965031863662055, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  10%|█         | 50/500 [05:11<45:01,  6.00s/it]

[I 2026-10-05 14:58:17,592] Trial 179 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017949179506555875, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  10%|█         | 51/500 [05:16<44:19,  5.92s/it]

[I 2026-10-05 14:58:23,328] Trial 180 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001995818416377401, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  10%|█         | 52/500 [05:22<43:16,  5.80s/it]

[I 2026-10-05 14:58:28,824] Trial 181 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013601607055905335, 'weight_decay': 1e-07, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  11%|█         | 53/500 [05:28<44:11,  5.93s/it]

[I 2026-10-05 14:58:35,073] Trial 182 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014170255511643782, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  11%|█         | 54/500 [05:33<42:36,  5.73s/it]

[I 2026-10-05 14:58:40,331] Trial 183 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0015932297466474965, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  11%|█         | 55/500 [05:40<44:15,  5.97s/it]

[I 2026-10-05 14:58:46,860] Trial 184 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013800850183714021, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  11%|█         | 56/500 [05:49<51:09,  6.91s/it]

[I 2026-10-05 14:58:55,977] Trial 185 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012291765239993832, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  11%|█▏        | 57/500 [05:55<49:50,  6.75s/it]

[I 2026-10-05 14:59:02,345] Trial 186 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012758507885884615, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  12%|█▏        | 58/500 [05:59<44:03,  5.98s/it]

[I 2026-10-05 14:59:06,537] Trial 187 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017394937394469361, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  12%|█▏        | 59/500 [06:06<45:39,  6.21s/it]

[I 2026-10-05 14:59:13,282] Trial 188 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013223214997603937, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  12%|█▏        | 60/500 [06:12<44:15,  6.03s/it]

[I 2026-10-05 14:59:18,908] Trial 189 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0014080236700249515, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  12%|█▏        | 61/500 [06:17<42:22,  5.79s/it]

[I 2026-10-05 14:59:24,130] Trial 190 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018534790028759836, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  12%|█▏        | 62/500 [06:23<41:44,  5.72s/it]

[I 2026-10-05 14:59:29,655] Trial 191 finished with value: 0.8204264870931538 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0013894784374462689, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  13%|█▎        | 63/500 [06:30<45:11,  6.20s/it]

[I 2026-10-05 14:59:37,017] Trial 192 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012127521832577003, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  13%|█▎        | 64/500 [06:36<44:55,  6.18s/it]

[I 2026-10-05 14:59:43,142] Trial 193 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001367081847101705, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  13%|█▎        | 65/500 [06:41<42:48,  5.90s/it]

[I 2026-10-05 14:59:48,401] Trial 194 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001701776648262778, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  13%|█▎        | 66/500 [06:47<42:42,  5.91s/it]

[I 2026-10-05 14:59:54,308] Trial 195 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014033898726786486, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  13%|█▎        | 67/500 [06:53<43:03,  5.97s/it]

[I 2026-10-05 15:00:00,417] Trial 196 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0015114677865549506, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  14%|█▎        | 68/500 [06:58<41:04,  5.70s/it]

[I 2026-10-05 15:00:05,503] Trial 197 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017504704268604741, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  14%|█▍        | 69/500 [07:04<40:20,  5.62s/it]

[I 2026-10-05 15:00:10,912] Trial 198 finished with value: 0.8125701459034792 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.001339424633106736, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  14%|█▍        | 70/500 [07:08<37:34,  5.24s/it]

[I 2026-10-05 15:00:15,290] Trial 199 finished with value: 0.8103254769921436 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001954707931391099, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  14%|█▍        | 71/500 [07:16<42:51,  6.00s/it]

[I 2026-10-05 15:00:23,039] Trial 200 finished with value: 0.8069584736251404 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001484775639965373, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  14%|█▍        | 72/500 [07:22<43:10,  6.05s/it]

[I 2026-10-05 15:00:29,225] Trial 201 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013665747600630192, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  15%|█▍        | 73/500 [07:27<41:05,  5.77s/it]

[I 2026-10-05 15:00:34,352] Trial 202 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016991982357450859, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  15%|█▍        | 74/500 [07:34<42:31,  5.99s/it]

[I 2026-10-05 15:00:40,849] Trial 203 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013846422263767985, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  15%|█▌        | 75/500 [07:40<43:58,  6.21s/it]

[I 2026-10-05 15:00:47,532] Trial 204 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013872627091409593, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  15%|█▌        | 76/500 [07:47<44:40,  6.32s/it]

[I 2026-10-05 15:00:54,151] Trial 205 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012618966855112957, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  15%|█▌        | 77/500 [07:56<49:16,  6.99s/it]

[I 2026-10-05 15:01:02,696] Trial 206 finished with value: 0.8103254769921436 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013890722323310718, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  16%|█▌        | 78/500 [08:02<46:50,  6.66s/it]

[I 2026-10-05 15:01:08,589] Trial 207 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017236236388399019, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  16%|█▌        | 79/500 [08:04<38:52,  5.54s/it]

[I 2026-10-05 15:01:11,520] Trial 208 finished with value: 0.8159371492704827 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013483192126646773, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  16%|█▌        | 80/500 [08:13<45:00,  6.43s/it]

[I 2026-10-05 15:01:20,025] Trial 209 finished with value: 0.8294051627384961 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001361131634420076, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  16%|█▌        | 81/500 [08:18<42:23,  6.07s/it]

[I 2026-10-05 15:01:25,255] Trial 210 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017477286478995153, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  16%|█▋        | 82/500 [08:24<42:38,  6.12s/it]

[I 2026-10-05 15:01:31,493] Trial 211 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013495635420162245, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  17%|█▋        | 83/500 [08:29<40:10,  5.78s/it]

[I 2026-10-05 15:01:36,478] Trial 212 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017787813564070637, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  17%|█▋        | 84/500 [08:37<44:46,  6.46s/it]

[I 2026-10-05 15:01:44,517] Trial 213 finished with value: 0.8125701459034792 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017676922358325546, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  17%|█▋        | 85/500 [08:46<48:45,  7.05s/it]

[I 2026-10-05 15:01:52,952] Trial 214 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.00134182398719249, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  17%|█▋        | 86/500 [08:52<47:01,  6.81s/it]

[I 2026-10-05 15:01:59,215] Trial 215 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017959479260481557, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  17%|█▋        | 87/500 [08:57<42:51,  6.23s/it]

[I 2026-10-05 15:02:04,070] Trial 216 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0022920327377664793, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  18%|█▊        | 88/500 [09:02<40:47,  5.94s/it]

[I 2026-10-05 15:02:09,343] Trial 217 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014882208527556189, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  18%|█▊        | 89/500 [09:07<38:25,  5.61s/it]

[I 2026-10-05 15:02:14,183] Trial 218 finished with value: 0.8215488215488215 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0013655426143326865, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  18%|█▊        | 90/500 [09:16<44:20,  6.49s/it]

[I 2026-10-05 15:02:22,719] Trial 219 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013421380497196467, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  18%|█▊        | 91/500 [09:20<40:46,  5.98s/it]

[I 2026-10-05 15:02:27,518] Trial 220 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0020721521988447344, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  18%|█▊        | 92/500 [09:27<41:38,  6.12s/it]

[I 2026-10-05 15:02:33,974] Trial 221 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013811116784437074, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  19%|█▊        | 93/500 [09:30<35:27,  5.23s/it]

[I 2026-10-05 15:02:37,109] Trial 222 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016936154937025351, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  19%|█▉        | 94/500 [09:39<41:58,  6.20s/it]

[I 2026-10-05 15:02:45,596] Trial 223 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012882354080786206, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  19%|█▉        | 95/500 [09:47<46:16,  6.86s/it]

[I 2026-10-05 15:02:53,974] Trial 224 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014099450017808477, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  19%|█▉        | 96/500 [09:53<44:57,  6.68s/it]

[I 2026-10-05 15:03:00,230] Trial 225 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001859113270568145, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  19%|█▉        | 97/500 [09:59<43:21,  6.46s/it]

[I 2026-10-05 15:03:06,164] Trial 226 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013820314882789057, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  20%|█▉        | 98/500 [10:08<48:36,  7.26s/it]

[I 2026-10-05 15:03:15,292] Trial 227 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013717567274864298, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  20%|█▉        | 99/500 [10:14<46:08,  6.90s/it]

[I 2026-10-05 15:03:21,380] Trial 228 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013563366076465046, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  20%|██        | 100/500 [10:21<45:36,  6.84s/it]

[I 2026-10-05 15:03:28,076] Trial 229 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012350421034745612, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  20%|██        | 101/500 [10:27<43:26,  6.53s/it]

[I 2026-10-05 15:03:33,889] Trial 230 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014467985460540243, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  20%|██        | 102/500 [10:32<41:03,  6.19s/it]

[I 2026-10-05 15:03:39,269] Trial 231 finished with value: 0.8114478114478114 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012392006589055278, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  21%|██        | 103/500 [10:38<41:07,  6.22s/it]

[I 2026-10-05 15:03:45,554] Trial 232 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001521009797276764, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  21%|██        | 104/500 [10:44<39:46,  6.03s/it]

[I 2026-10-05 15:03:51,138] Trial 233 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013505086723466279, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  21%|██        | 105/500 [10:52<44:25,  6.75s/it]

[I 2026-10-05 15:03:59,557] Trial 234 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013217213924096762, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  21%|██        | 106/500 [10:56<37:40,  5.74s/it]

[I 2026-10-05 15:04:02,953] Trial 235 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016775663192402145, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  21%|██▏       | 107/500 [11:01<36:48,  5.62s/it]

[I 2026-10-05 15:04:08,295] Trial 236 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014262231385035644, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  22%|██▏       | 108/500 [11:12<47:43,  7.30s/it]

[I 2026-10-05 15:04:19,530] Trial 237 finished with value: 0.8136924803591471 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013035353295635143, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  22%|██▏       | 109/500 [11:17<41:20,  6.34s/it]

[I 2026-10-05 15:04:23,630] Trial 238 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018477812830215259, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  22%|██▏       | 110/500 [11:23<40:54,  6.29s/it]

[I 2026-10-05 15:04:29,808] Trial 239 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014662240147587816, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  22%|██▏       | 111/500 [11:35<52:58,  8.17s/it]

[I 2026-10-05 15:04:42,354] Trial 240 finished with value: 0.8148148148148149 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013528489146658038, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  22%|██▏       | 112/500 [11:42<49:05,  7.59s/it]

[I 2026-10-05 15:04:48,593] Trial 241 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013400480810567494, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  23%|██▎       | 113/500 [11:47<45:35,  7.07s/it]

[I 2026-10-05 15:04:54,448] Trial 242 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014733248068309684, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  23%|██▎       | 114/500 [11:53<43:35,  6.78s/it]

[I 2026-10-05 15:05:00,542] Trial 243 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013577851689112925, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  23%|██▎       | 115/500 [11:58<39:44,  6.19s/it]

[I 2026-10-05 15:05:05,376] Trial 244 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0018208489256710677, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  23%|██▎       | 116/500 [12:05<39:56,  6.24s/it]

[I 2026-10-05 15:05:11,722] Trial 245 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001283496852436363, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  23%|██▎       | 117/500 [12:10<38:05,  5.97s/it]

[I 2026-10-05 15:05:17,052] Trial 246 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016478799434038606, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  24%|██▎       | 118/500 [12:16<38:47,  6.09s/it]

[I 2026-10-05 15:05:23,436] Trial 247 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013299266300535225, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  24%|██▍       | 119/500 [12:24<40:43,  6.41s/it]

[I 2026-10-05 15:05:30,592] Trial 248 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012487546171087965, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  24%|██▍       | 120/500 [12:30<41:12,  6.51s/it]

[I 2026-10-05 15:05:37,320] Trial 249 finished with value: 0.8170594837261506 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0012010652203908831, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  24%|██▍       | 121/500 [12:37<41:23,  6.55s/it]

[I 2026-10-05 15:05:43,988] Trial 250 finished with value: 0.8136924803591471 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0012428928211720158, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  24%|██▍       | 122/500 [12:42<38:42,  6.15s/it]

[I 2026-10-05 15:05:49,181] Trial 251 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016182933921724066, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  25%|██▍       | 123/500 [12:48<38:30,  6.13s/it]

[I 2026-10-05 15:05:55,272] Trial 252 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013562932062794264, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  25%|██▍       | 124/500 [12:55<39:02,  6.23s/it]

[I 2026-10-05 15:06:01,734] Trial 253 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.00136926231734231, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  25%|██▌       | 125/500 [13:01<39:20,  6.29s/it]

[I 2026-10-05 15:06:08,177] Trial 254 finished with value: 0.8260381593714926 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014193861254208503, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  25%|██▌       | 126/500 [13:05<34:47,  5.58s/it]

[I 2026-10-05 15:06:12,098] Trial 255 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0024269097543868578, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  25%|██▌       | 127/500 [13:11<36:00,  5.79s/it]

[I 2026-10-05 15:06:18,372] Trial 256 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013364356254035599, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  26%|██▌       | 128/500 [13:16<33:21,  5.38s/it]

[I 2026-10-05 15:06:22,799] Trial 257 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013434252446349758, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  26%|██▌       | 129/500 [13:20<30:47,  4.98s/it]

[I 2026-10-05 15:06:26,842] Trial 258 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013589661763289721, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  26%|██▌       | 130/500 [13:28<37:11,  6.03s/it]

[I 2026-10-05 15:06:35,326] Trial 259 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001326389309571164, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  26%|██▌       | 131/500 [13:33<34:37,  5.63s/it]

[I 2026-10-05 15:06:40,021] Trial 260 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0019821004747012545, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  26%|██▋       | 132/500 [13:38<33:45,  5.50s/it]

[I 2026-10-05 15:06:45,228] Trial 261 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012052990954600125, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  27%|██▋       | 133/500 [13:41<29:18,  4.79s/it]

[I 2026-10-05 15:06:48,357] Trial 262 finished with value: 0.8114478114478114 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012660808193047288, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  27%|██▋       | 134/500 [13:48<32:51,  5.39s/it]

[I 2026-10-05 15:06:55,131] Trial 263 finished with value: 0.8294051627384961 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012524030063559876, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  27%|██▋       | 135/500 [13:52<30:18,  4.98s/it]

[I 2026-10-05 15:06:59,172] Trial 264 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0021362698134677637, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  27%|██▋       | 136/500 [14:02<39:40,  6.54s/it]

[I 2026-10-05 15:07:09,344] Trial 265 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012430704655055826, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  27%|██▋       | 137/500 [14:08<38:25,  6.35s/it]

[I 2026-10-05 15:07:15,254] Trial 266 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0012340335634903998, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  28%|██▊       | 138/500 [14:15<38:58,  6.46s/it]

[I 2026-10-05 15:07:21,965] Trial 267 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001266049261748688, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  28%|██▊       | 139/500 [14:21<38:18,  6.37s/it]

[I 2026-10-05 15:07:28,115] Trial 268 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001748977395918973, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  28%|██▊       | 140/500 [14:27<38:07,  6.35s/it]

[I 2026-10-05 15:07:34,442] Trial 269 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013278485156896374, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  28%|██▊       | 141/500 [14:32<35:02,  5.86s/it]

[I 2026-10-05 15:07:39,137] Trial 270 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0018615013646775633, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  28%|██▊       | 142/500 [14:35<30:30,  5.11s/it]

[I 2026-10-05 15:07:42,512] Trial 271 finished with value: 0.8103254769921436 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014505565359155964, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  29%|██▊       | 143/500 [14:42<32:22,  5.44s/it]

[I 2026-10-05 15:07:48,715] Trial 272 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013254295800610167, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  29%|██▉       | 144/500 [14:48<33:51,  5.71s/it]

[I 2026-10-05 15:07:55,047] Trial 273 finished with value: 0.8294051627384961 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001295689321530983, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  29%|██▉       | 145/500 [14:54<34:40,  5.86s/it]

[I 2026-10-05 15:08:01,269] Trial 274 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013359642387837864, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  29%|██▉       | 146/500 [14:57<29:27,  4.99s/it]

[I 2026-10-05 15:08:04,236] Trial 275 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013123983285322023, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  29%|██▉       | 147/500 [15:03<31:30,  5.36s/it]

[I 2026-10-05 15:08:10,439] Trial 276 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018081143844200398, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  30%|██▉       | 148/500 [15:07<28:08,  4.80s/it]

[I 2026-10-05 15:08:13,933] Trial 277 finished with value: 0.8035914702581369 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0013264831355220038, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  30%|██▉       | 149/500 [15:10<25:31,  4.36s/it]

[I 2026-10-05 15:08:17,277] Trial 278 finished with value: 0.8159371492704826 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013540763726876681, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  30%|███       | 150/500 [15:18<31:28,  5.40s/it]

[I 2026-10-05 15:08:25,083] Trial 279 finished with value: 0.8114478114478114 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013138206584444177, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  30%|███       | 151/500 [15:24<33:14,  5.72s/it]

[I 2026-10-05 15:08:31,548] Trial 280 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013576483147203638, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  30%|███       | 152/500 [15:31<34:54,  6.02s/it]

[I 2026-10-05 15:08:38,278] Trial 281 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017405878587403202, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  31%|███       | 153/500 [15:39<37:59,  6.57s/it]

[I 2026-10-05 15:08:46,127] Trial 282 finished with value: 0.8170594837261503 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013321893960489216, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 5, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  31%|███       | 154/500 [15:48<41:49,  7.25s/it]

[I 2026-10-05 15:08:54,975] Trial 283 finished with value: 0.8159371492704826 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012609450693868386, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  31%|███       | 155/500 [15:54<40:09,  6.98s/it]

[I 2026-10-05 15:09:01,334] Trial 284 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013126235604970402, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  31%|███       | 156/500 [16:01<38:55,  6.79s/it]

[I 2026-10-05 15:09:07,668] Trial 285 finished with value: 0.8294051627384961 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012956699304406405, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  31%|███▏      | 157/500 [16:07<37:34,  6.57s/it]

[I 2026-10-05 15:09:13,733] Trial 286 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012966789998999529, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  32%|███▏      | 158/500 [16:12<34:44,  6.10s/it]

[I 2026-10-05 15:09:18,721] Trial 287 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0021463894160789008, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  32%|███▏      | 159/500 [16:17<32:52,  5.79s/it]

[I 2026-10-05 15:09:23,776] Trial 288 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017854646439657133, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  32%|███▏      | 160/500 [16:23<33:48,  5.97s/it]

[I 2026-10-05 15:09:30,166] Trial 289 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001236873180689428, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  32%|███▏      | 161/500 [16:31<37:51,  6.70s/it]

[I 2026-10-05 15:09:38,582] Trial 290 finished with value: 0.809203142536476 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001374977271809845, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  32%|███▏      | 162/500 [16:36<34:30,  6.12s/it]

[I 2026-10-05 15:09:43,363] Trial 291 finished with value: 0.8215488215488215 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0013248458157483708, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  33%|███▎      | 163/500 [16:41<31:40,  5.64s/it]

[I 2026-10-05 15:09:47,873] Trial 292 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0018875224987768536, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  33%|███▎      | 164/500 [16:47<33:23,  5.96s/it]

[I 2026-10-05 15:09:54,587] Trial 293 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013259199880645198, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  33%|███▎      | 165/500 [16:53<33:11,  5.95s/it]

[I 2026-10-05 15:10:00,493] Trial 294 finished with value: 0.8159371492704826 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.00186523309891968, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  33%|███▎      | 166/500 [17:04<41:03,  7.38s/it]

[I 2026-10-05 15:10:11,208] Trial 295 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012271329901412085, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  33%|███▎      | 167/500 [17:09<37:37,  6.78s/it]

[I 2026-10-05 15:10:16,594] Trial 296 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0019661664850084536, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  34%|███▎      | 168/500 [17:16<36:53,  6.67s/it]

[I 2026-10-05 15:10:23,003] Trial 297 finished with value: 0.8249158249158248 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012349003396143828, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  34%|███▍      | 169/500 [17:23<37:27,  6.79s/it]

[I 2026-10-05 15:10:30,078] Trial 298 finished with value: 0.8159371492704827 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013853992779080365, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  34%|███▍      | 170/500 [17:30<37:14,  6.77s/it]

[I 2026-10-05 15:10:36,806] Trial 299 finished with value: 0.8125701459034792 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0019045656865928078, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  34%|███▍      | 171/500 [17:34<32:46,  5.98s/it]

[I 2026-10-05 15:10:40,929] Trial 300 finished with value: 0.8159371492704827 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018172180303281322, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  34%|███▍      | 172/500 [17:40<32:51,  6.01s/it]

[I 2026-10-05 15:10:47,019] Trial 301 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014466429223596333, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  35%|███▍      | 173/500 [17:44<29:17,  5.37s/it]

[I 2026-10-05 15:10:50,910] Trial 302 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017435584726733858, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  35%|███▍      | 174/500 [17:48<28:02,  5.16s/it]

[I 2026-10-05 15:10:55,569] Trial 303 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018011675081797374, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  35%|███▌      | 175/500 [17:54<28:35,  5.28s/it]

[I 2026-10-05 15:11:01,121] Trial 304 finished with value: 0.8170594837261506 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0017633845170554182, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  35%|███▌      | 176/500 [18:01<30:37,  5.67s/it]

[I 2026-10-05 15:11:07,706] Trial 305 finished with value: 0.8136924803591471 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017446061344615867, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  35%|███▌      | 177/500 [18:07<31:47,  5.90s/it]

[I 2026-10-05 15:11:14,157] Trial 306 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014029934383078928, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  36%|███▌      | 178/500 [18:13<32:18,  6.02s/it]

[I 2026-10-05 15:11:20,452] Trial 307 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001229488942090695, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  36%|███▌      | 179/500 [18:18<30:14,  5.65s/it]

[I 2026-10-05 15:11:25,248] Trial 308 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017260887612668327, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  36%|███▌      | 180/500 [18:23<29:28,  5.53s/it]

[I 2026-10-05 15:11:30,474] Trial 309 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017948757062581228, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  36%|███▌      | 181/500 [18:29<28:55,  5.44s/it]

[I 2026-10-05 15:11:35,710] Trial 310 finished with value: 0.8260381593714926 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017736808492713136, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  36%|███▋      | 182/500 [18:34<29:05,  5.49s/it]

[I 2026-10-05 15:11:41,315] Trial 311 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012838864215923688, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  37%|███▋      | 183/500 [18:37<25:20,  4.80s/it]

[I 2026-10-05 15:11:44,495] Trial 312 finished with value: 0.818181818181818 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017636834806502057, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  37%|███▋      | 184/500 [18:42<25:25,  4.83s/it]

[I 2026-10-05 15:11:49,391] Trial 313 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.002292081099840134, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  37%|███▋      | 185/500 [18:50<29:44,  5.67s/it]

[I 2026-10-05 15:11:57,018] Trial 314 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013694372817673558, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 5, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  37%|███▋      | 186/500 [18:56<30:39,  5.86s/it]

[I 2026-10-05 15:12:03,326] Trial 315 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012830986222325802, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  37%|███▋      | 187/500 [19:02<30:22,  5.82s/it]

[I 2026-10-05 15:12:09,069] Trial 316 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013928269542229424, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  38%|███▊      | 188/500 [19:09<31:58,  6.15s/it]

[I 2026-10-05 15:12:15,973] Trial 317 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014798067025270968, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  38%|███▊      | 189/500 [19:12<27:31,  5.31s/it]

[I 2026-10-05 15:12:19,327] Trial 318 finished with value: 0.8103254769921436 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018588242965698108, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  38%|███▊      | 190/500 [19:17<26:36,  5.15s/it]

[I 2026-10-05 15:12:24,103] Trial 319 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0019008470917035902, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  38%|███▊      | 191/500 [19:21<25:18,  4.92s/it]

[I 2026-10-05 15:12:28,469] Trial 320 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0018371039199718046, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  38%|███▊      | 192/500 [19:27<26:47,  5.22s/it]

[I 2026-10-05 15:12:34,396] Trial 321 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0019273655942821674, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  39%|███▊      | 193/500 [19:34<28:19,  5.53s/it]

[I 2026-10-05 15:12:40,670] Trial 322 finished with value: 0.8114478114478114 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013735727138268693, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  39%|███▉      | 194/500 [19:37<24:21,  4.78s/it]

[I 2026-10-05 15:12:43,674] Trial 323 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0018217324988480709, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  39%|███▉      | 195/500 [19:42<25:51,  5.09s/it]

[I 2026-10-05 15:12:49,487] Trial 324 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018634284052019003, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  39%|███▉      | 196/500 [19:47<24:38,  4.86s/it]

[I 2026-10-05 15:12:53,828] Trial 325 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0022516804523646985, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  39%|███▉      | 197/500 [19:53<26:49,  5.31s/it]

[I 2026-10-05 15:13:00,181] Trial 326 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0016368589396104408, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  40%|███▉      | 198/500 [20:02<31:58,  6.35s/it]

[I 2026-10-05 15:13:08,963] Trial 327 finished with value: 0.8103254769921436 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012812265659545678, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  40%|███▉      | 199/500 [20:07<29:46,  5.93s/it]

[I 2026-10-05 15:13:13,923] Trial 328 finished with value: 0.8136924803591471 and parameters: {'activation': 'silu', 'batch_size': 64, 'learning_rate': 0.001333281292971794, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  40%|████      | 200/500 [20:13<29:25,  5.88s/it]

[I 2026-10-05 15:13:19,693] Trial 329 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013638043720633991, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  40%|████      | 201/500 [20:22<35:16,  7.08s/it]

[I 2026-10-05 15:13:29,552] Trial 330 finished with value: 0.809203142536476 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013368749756644178, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  40%|████      | 202/500 [20:26<29:29,  5.94s/it]

[I 2026-10-05 15:13:32,833] Trial 331 finished with value: 0.8170594837261503 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012723405339395307, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  41%|████      | 203/500 [20:30<27:35,  5.57s/it]

[I 2026-10-05 15:13:37,554] Trial 332 finished with value: 0.8035914702581369 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001308424432999914, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  41%|████      | 204/500 [20:38<30:59,  6.28s/it]

[I 2026-10-05 15:13:45,473] Trial 333 finished with value: 0.6790123456790124 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0013816231906560001, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  41%|████      | 205/500 [20:43<29:06,  5.92s/it]

[I 2026-10-05 15:13:50,567] Trial 334 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001857779650547364, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  41%|████      | 206/500 [20:48<26:29,  5.41s/it]

[I 2026-10-05 15:13:54,776] Trial 335 finished with value: 0.8148148148148149 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017816091193061994, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  41%|████▏     | 207/500 [20:52<25:16,  5.18s/it]

[I 2026-10-05 15:13:59,417] Trial 336 finished with value: 0.8058361391694726 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.001311054936762377, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  42%|████▏     | 208/500 [20:58<26:09,  5.38s/it]

[I 2026-10-05 15:14:05,253] Trial 337 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0015003907388392382, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  42%|████▏     | 209/500 [21:02<23:36,  4.87s/it]

[I 2026-10-05 15:14:08,940] Trial 338 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013757511282401506, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  42%|████▏     | 210/500 [21:08<26:00,  5.38s/it]

[I 2026-10-05 15:14:15,515] Trial 339 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.00126484436112732, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  42%|████▏     | 211/500 [21:16<28:40,  5.95s/it]

[I 2026-10-05 15:14:22,808] Trial 340 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012498701877127105, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  42%|████▏     | 212/500 [21:20<25:59,  5.42s/it]

[I 2026-10-05 15:14:26,965] Trial 341 finished with value: 0.8069584736251403 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013218498071125844, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  43%|████▎     | 213/500 [21:28<29:11,  6.10s/it]

[I 2026-10-05 15:14:34,668] Trial 342 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014583244019909945, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  43%|████▎     | 214/500 [21:35<30:19,  6.36s/it]

[I 2026-10-05 15:14:41,638] Trial 343 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0016855780229847101, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  43%|████▎     | 215/500 [21:42<31:19,  6.60s/it]

[I 2026-10-05 15:14:48,780] Trial 344 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013466910401266003, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  43%|████▎     | 216/500 [21:48<30:55,  6.53s/it]

[I 2026-10-05 15:14:55,165] Trial 345 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012804145330587065, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  43%|████▎     | 217/500 [21:56<32:28,  6.89s/it]

[I 2026-10-05 15:15:02,877] Trial 346 finished with value: 0.8148148148148148 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013645715251818366, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 5, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  44%|████▎     | 218/500 [22:02<31:08,  6.63s/it]

[I 2026-10-05 15:15:08,894] Trial 347 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.002210184514077914, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  44%|████▍     | 219/500 [22:10<33:08,  7.08s/it]

[I 2026-10-05 15:15:17,026] Trial 348 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013708103560620326, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  44%|████▍     | 220/500 [22:13<27:45,  5.95s/it]

[I 2026-10-05 15:15:20,345] Trial 349 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013248123190572382, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  44%|████▍     | 221/500 [22:25<36:12,  7.79s/it]

[I 2026-10-05 15:15:32,418] Trial 350 finished with value: 0.8058361391694726 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013557810870534336, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  44%|████▍     | 222/500 [22:29<29:55,  6.46s/it]

[I 2026-10-05 15:15:35,773] Trial 351 finished with value: 0.8159371492704826 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012964280169035945, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  45%|████▍     | 223/500 [22:36<30:59,  6.71s/it]

[I 2026-10-05 15:15:43,085] Trial 352 finished with value: 0.8136924803591471 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013163640216677177, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  45%|████▍     | 224/500 [22:39<25:49,  5.61s/it]

[I 2026-10-05 15:15:46,130] Trial 353 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014485548576417438, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  45%|████▌     | 225/500 [22:48<30:19,  6.62s/it]

[I 2026-10-05 15:15:55,089] Trial 354 finished with value: 0.8159371492704827 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0015931731669621273, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  45%|████▌     | 226/500 [22:53<28:07,  6.16s/it]

[I 2026-10-05 15:16:00,177] Trial 355 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0017837458472825137, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  45%|████▌     | 227/500 [22:58<26:26,  5.81s/it]

[I 2026-10-05 15:16:05,176] Trial 356 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014365120053247294, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  46%|████▌     | 228/500 [23:07<30:12,  6.66s/it]

[I 2026-10-05 15:16:13,824] Trial 357 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001310742637806444, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  46%|████▌     | 229/500 [23:10<26:08,  5.79s/it]

[I 2026-10-05 15:16:17,577] Trial 358 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0012585929673459232, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  46%|████▌     | 230/500 [23:15<24:41,  5.49s/it]

[I 2026-10-05 15:16:22,360] Trial 359 finished with value: 0.8215488215488215 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012891080017176004, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  46%|████▌     | 231/500 [23:22<25:57,  5.79s/it]

[I 2026-10-05 15:16:28,857] Trial 360 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0014023697098151091, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  46%|████▋     | 232/500 [23:29<27:45,  6.22s/it]

[I 2026-10-05 15:16:36,067] Trial 361 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001209915401266828, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  47%|████▋     | 233/500 [23:32<23:51,  5.36s/it]

[I 2026-10-05 15:16:39,431] Trial 362 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001337084318549697, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  47%|████▋     | 234/500 [23:37<22:58,  5.18s/it]

[I 2026-10-05 15:16:44,196] Trial 363 finished with value: 0.8226711560044894 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0013249084420463423, 'weight_decay': 1e-07, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  47%|████▋     | 235/500 [23:40<20:19,  4.60s/it]

[I 2026-10-05 15:16:47,451] Trial 364 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013415540175781583, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  47%|████▋     | 236/500 [23:51<28:33,  6.49s/it]

[I 2026-10-05 15:16:58,344] Trial 365 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0020558588859688844, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  47%|████▋     | 237/500 [24:00<31:29,  7.18s/it]

[I 2026-10-05 15:17:07,147] Trial 366 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0015663711898998589, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  48%|████▊     | 238/500 [24:08<32:05,  7.35s/it]

[I 2026-10-05 15:17:14,876] Trial 367 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018207757341181883, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  48%|████▊     | 239/500 [24:13<29:47,  6.85s/it]

[I 2026-10-05 15:17:20,554] Trial 368 finished with value: 0.8193041526374859 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0013025380428137, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  48%|████▊     | 240/500 [24:19<27:25,  6.33s/it]

[I 2026-10-05 15:17:25,668] Trial 369 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.002395166143331955, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  48%|████▊     | 241/500 [24:24<26:14,  6.08s/it]

[I 2026-10-05 15:17:31,171] Trial 370 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0019443315414373512, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  48%|████▊     | 242/500 [24:32<28:42,  6.68s/it]

[I 2026-10-05 15:17:39,237] Trial 371 finished with value: 0.8181818181818182 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018441216654065302, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  49%|████▊     | 243/500 [24:37<26:03,  6.09s/it]

[I 2026-10-05 15:17:43,948] Trial 372 finished with value: 0.8148148148148149 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.001523694644784098, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  49%|████▉     | 244/500 [24:45<28:43,  6.73s/it]

[I 2026-10-05 15:17:52,185] Trial 373 finished with value: 0.8181818181818182 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001393470254194907, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  49%|████▉     | 245/500 [24:50<26:40,  6.28s/it]

[I 2026-10-05 15:17:57,399] Trial 374 finished with value: 0.7497194163860831 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0012497784585877643, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  49%|████▉     | 246/500 [24:58<28:08,  6.65s/it]

[I 2026-10-05 15:18:04,914] Trial 375 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013930730004169322, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 5, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  49%|████▉     | 247/500 [25:01<23:25,  5.56s/it]

[I 2026-10-05 15:18:07,923] Trial 376 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012068264810402127, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  50%|████▉     | 248/500 [25:04<19:56,  4.75s/it]

[I 2026-10-05 15:18:10,785] Trial 377 finished with value: 0.8148148148148149 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.00191352107100288, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  50%|████▉     | 249/500 [25:09<20:37,  4.93s/it]

[I 2026-10-05 15:18:16,139] Trial 378 finished with value: 0.8058361391694725 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.002353899497062992, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  50%|█████     | 250/500 [25:15<21:55,  5.26s/it]

[I 2026-10-05 15:18:22,173] Trial 379 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013430525432741006, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  50%|█████     | 251/500 [25:19<20:03,  4.83s/it]

[I 2026-10-05 15:18:26,014] Trial 380 finished with value: 0.8114478114478114 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014254451240041342, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  50%|█████     | 252/500 [25:25<21:14,  5.14s/it]

[I 2026-10-05 15:18:31,863] Trial 381 finished with value: 0.8136924803591471 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0019319302950789976, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  51%|█████     | 253/500 [25:28<18:12,  4.43s/it]

[I 2026-10-05 15:18:34,618] Trial 382 finished with value: 0.7508417508417509 and parameters: {'activation': 'squared_relu', 'batch_size': 64, 'learning_rate': 0.0018560515175950608, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  51%|█████     | 254/500 [25:30<16:17,  3.97s/it]

[I 2026-10-05 15:18:37,548] Trial 383 finished with value: 0.7530864197530865 and parameters: {'activation': 'squared_relu', 'batch_size': 64, 'learning_rate': 0.0017853835810021637, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  51%|█████     | 255/500 [25:37<18:50,  4.61s/it]

[I 2026-10-05 15:18:43,649] Trial 384 finished with value: 0.7384960718294051 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0013792695570379132, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  51%|█████     | 256/500 [25:40<17:24,  4.28s/it]

[I 2026-10-05 15:18:47,152] Trial 385 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001242233062009323, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  51%|█████▏    | 257/500 [25:46<19:05,  4.72s/it]

[I 2026-10-05 15:18:52,885] Trial 386 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018575757650608708, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  52%|█████▏    | 258/500 [25:52<20:26,  5.07s/it]

[I 2026-10-05 15:18:58,769] Trial 387 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0012818734150478513, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  52%|█████▏    | 259/500 [25:58<21:19,  5.31s/it]

[I 2026-10-05 15:19:04,640] Trial 388 finished with value: 0.8204264870931538 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.00190504541335652, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  52%|█████▏    | 260/500 [26:04<22:07,  5.53s/it]

[I 2026-10-05 15:19:10,693] Trial 389 finished with value: 0.829405162738496 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013144937360876376, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  52%|█████▏    | 261/500 [26:08<20:19,  5.10s/it]

[I 2026-10-05 15:19:14,787] Trial 390 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017900443773718226, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  52%|█████▏    | 262/500 [26:12<18:50,  4.75s/it]

[I 2026-10-05 15:19:18,731] Trial 391 finished with value: 0.8159371492704826 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012533209420533076, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  53%|█████▎    | 263/500 [26:18<20:19,  5.14s/it]

[I 2026-10-05 15:19:24,789] Trial 392 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013247831938014818, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  53%|█████▎    | 264/500 [26:26<23:49,  6.06s/it]

[I 2026-10-05 15:19:32,975] Trial 393 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014013027743722884, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  53%|█████▎    | 265/500 [26:31<22:15,  5.68s/it]

[I 2026-10-05 15:19:37,787] Trial 394 finished with value: 0.8204264870931537 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012530220714366738, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  53%|█████▎    | 266/500 [26:36<21:08,  5.42s/it]

[I 2026-10-05 15:19:42,596] Trial 395 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018023612365757873, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  53%|█████▎    | 267/500 [26:41<20:42,  5.33s/it]

[I 2026-10-05 15:19:47,730] Trial 396 finished with value: 0.818181818181818 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013607101310585627, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  54%|█████▎    | 268/500 [26:47<21:26,  5.54s/it]

[I 2026-10-05 15:19:53,759] Trial 397 finished with value: 0.8024691358024691 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0012367065622458596, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  54%|█████▍    | 269/500 [26:52<20:52,  5.42s/it]

[I 2026-10-05 15:19:58,902] Trial 398 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.001379901695756444, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  54%|█████▍    | 270/500 [26:57<20:07,  5.25s/it]

[I 2026-10-05 15:20:03,745] Trial 399 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001510050543581524, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  54%|█████▍    | 271/500 [27:03<20:44,  5.44s/it]

[I 2026-10-05 15:20:09,617] Trial 400 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0012700402911613837, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  54%|█████▍    | 272/500 [27:10<23:24,  6.16s/it]

[I 2026-10-05 15:20:17,468] Trial 401 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013272703295809135, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  55%|█████▍    | 273/500 [27:19<26:04,  6.89s/it]

[I 2026-10-05 15:20:26,072] Trial 402 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013382813723272116, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  55%|█████▍    | 274/500 [27:22<21:33,  5.72s/it]

[I 2026-10-05 15:20:29,063] Trial 403 finished with value: 0.8204264870931538 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012893435767686598, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  55%|█████▌    | 275/500 [27:28<21:50,  5.83s/it]

[I 2026-10-05 15:20:35,133] Trial 404 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013436237011557502, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  55%|█████▌    | 276/500 [27:31<19:03,  5.10s/it]

[I 2026-10-05 15:20:38,548] Trial 405 finished with value: 0.8294051627384961 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013745307929181286, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  55%|█████▌    | 277/500 [27:34<16:26,  4.42s/it]

[I 2026-10-05 15:20:41,391] Trial 406 finished with value: 0.8159371492704826 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0014392045916152222, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.1}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  56%|█████▌    | 278/500 [27:38<15:21,  4.15s/it]

[I 2026-10-05 15:20:44,901] Trial 407 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013195571866995433, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  56%|█████▌    | 279/500 [27:41<14:06,  3.83s/it]

[I 2026-10-05 15:20:47,982] Trial 408 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013640694286587022, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  56%|█████▌    | 280/500 [27:45<14:49,  4.04s/it]

[I 2026-10-05 15:20:52,519] Trial 409 finished with value: 0.8069584736251403 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001428837631167856, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  56%|█████▌    | 281/500 [27:57<22:39,  6.21s/it]

[I 2026-10-05 15:21:03,782] Trial 410 finished with value: 0.8148148148148148 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001318616464921789, 'weight_decay': 0.0001, 'dropout': 0.15000000000000002, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  56%|█████▋    | 282/500 [28:07<26:49,  7.38s/it]

[I 2026-10-05 15:21:13,913] Trial 411 finished with value: 0.8159371492704826 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013465813659298569, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  57%|█████▋    | 283/500 [28:15<27:47,  7.69s/it]

[I 2026-10-05 15:21:22,303] Trial 412 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013903177920763464, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  57%|█████▋    | 284/500 [28:22<27:02,  7.51s/it]

[I 2026-10-05 15:21:29,400] Trial 413 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001260992502499395, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  57%|█████▋    | 285/500 [28:29<25:35,  7.14s/it]

[I 2026-10-05 15:21:35,687] Trial 414 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012938757232513367, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  57%|█████▋    | 286/500 [28:35<24:13,  6.79s/it]

[I 2026-10-05 15:21:41,666] Trial 415 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018523637189989796, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  57%|█████▋    | 287/500 [28:38<20:25,  5.76s/it]

[I 2026-10-05 15:21:45,003] Trial 416 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014057202327798259, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  58%|█████▊    | 288/500 [28:44<20:38,  5.84s/it]

[I 2026-10-05 15:21:51,050] Trial 417 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001210473334865878, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  58%|█████▊    | 289/500 [28:48<18:31,  5.27s/it]

[I 2026-10-05 15:21:54,973] Trial 418 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013720043546258719, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  58%|█████▊    | 290/500 [28:58<23:44,  6.78s/it]

[I 2026-10-05 15:22:05,290] Trial 419 finished with value: 0.8114478114478114 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013163164329307066, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  58%|█████▊    | 291/500 [29:09<28:20,  8.14s/it]

[I 2026-10-05 15:22:16,588] Trial 420 finished with value: 0.8136924803591471 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013665288204269112, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  58%|█████▊    | 292/500 [29:19<29:07,  8.40s/it]

[I 2026-10-05 15:22:25,602] Trial 421 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013647823559430176, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  59%|█████▊    | 293/500 [29:22<23:24,  6.78s/it]

[I 2026-10-05 15:22:28,610] Trial 422 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013655218119608765, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  59%|█████▉    | 294/500 [29:28<22:41,  6.61s/it]

[I 2026-10-05 15:22:34,806] Trial 423 finished with value: 0.8271604938271606 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001821826878266994, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  59%|█████▉    | 295/500 [29:30<18:25,  5.39s/it]

[I 2026-10-05 15:22:37,361] Trial 424 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018867701025884847, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  59%|█████▉    | 296/500 [29:36<18:59,  5.59s/it]

[I 2026-10-05 15:22:43,403] Trial 425 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013011167153685788, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  59%|█████▉    | 297/500 [29:39<16:20,  4.83s/it]

[I 2026-10-05 15:22:46,466] Trial 426 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013819474275876622, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  60%|█████▉    | 298/500 [29:50<21:38,  6.43s/it]

[I 2026-10-05 15:22:56,626] Trial 427 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001359164046032602, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  60%|█████▉    | 299/500 [29:54<19:42,  5.88s/it]

[I 2026-10-05 15:23:01,236] Trial 428 finished with value: 0.8215488215488217 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013293449914795505, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  60%|██████    | 300/500 [29:58<17:50,  5.35s/it]

[I 2026-10-05 15:23:05,354] Trial 429 finished with value: 0.8181818181818182 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0020713004987642967, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  60%|██████    | 301/500 [30:04<18:05,  5.46s/it]

[I 2026-10-05 15:23:11,051] Trial 430 finished with value: 0.8260381593714926 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012779847925899872, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  60%|██████    | 302/500 [30:10<19:04,  5.78s/it]

[I 2026-10-05 15:23:17,586] Trial 431 finished with value: 0.8294051627384961 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012996662318803672, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  61%|██████    | 303/500 [30:17<19:29,  5.94s/it]

[I 2026-10-05 15:23:23,887] Trial 432 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012783649601940887, 'weight_decay': 1e-07, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  61%|██████    | 304/500 [30:23<19:56,  6.11s/it]

[I 2026-10-05 15:23:30,385] Trial 433 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001299476916259489, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  61%|██████    | 305/500 [30:27<17:36,  5.42s/it]

[I 2026-10-05 15:23:34,196] Trial 434 finished with value: 0.8181818181818182 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013675277451375436, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  61%|██████    | 306/500 [30:34<18:31,  5.73s/it]

[I 2026-10-05 15:23:40,656] Trial 435 finished with value: 0.8249158249158248 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012898942758636886, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  61%|██████▏   | 307/500 [30:38<17:31,  5.45s/it]

[I 2026-10-05 15:23:45,454] Trial 436 finished with value: 0.8047138047138048 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018402309346946138, 'weight_decay': 1e-07, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  62%|██████▏   | 308/500 [30:41<15:07,  4.73s/it]

[I 2026-10-05 15:23:48,494] Trial 437 finished with value: 0.8170594837261503 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012687660623518923, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  62%|██████▏   | 309/500 [30:44<13:22,  4.20s/it]

[I 2026-10-05 15:23:51,470] Trial 438 finished with value: 0.8193041526374859 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014398631372206806, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  62%|██████▏   | 310/500 [30:55<19:20,  6.11s/it]

[I 2026-10-05 15:24:02,023] Trial 439 finished with value: 0.8114478114478114 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014233930754250917, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  62%|██████▏   | 311/500 [31:03<20:53,  6.63s/it]

[I 2026-10-05 15:24:09,879] Trial 440 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013574507595810659, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  62%|██████▏   | 312/500 [31:07<18:16,  5.83s/it]

[I 2026-10-05 15:24:13,848] Trial 441 finished with value: 0.8193041526374859 and parameters: {'activation': 'gelu', 'batch_size': 64, 'learning_rate': 0.001362998358444683, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  63%|██████▎   | 313/500 [31:13<18:53,  6.06s/it]

[I 2026-10-05 15:24:20,449] Trial 442 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0022775323195059695, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  63%|██████▎   | 314/500 [31:18<17:01,  5.49s/it]

[I 2026-10-05 15:24:24,604] Trial 443 finished with value: 0.8305274971941637 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0024659843265906808, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  63%|██████▎   | 315/500 [31:22<15:55,  5.17s/it]

[I 2026-10-05 15:24:29,017] Trial 444 finished with value: 0.809203142536476 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012655201591275946, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  63%|██████▎   | 316/500 [31:28<16:47,  5.47s/it]

[I 2026-10-05 15:24:35,204] Trial 445 finished with value: 0.8294051627384961 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0016556192508599952, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  63%|██████▎   | 317/500 [31:34<17:21,  5.69s/it]

[I 2026-10-05 15:24:41,406] Trial 446 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015324576435868688, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  64%|██████▎   | 318/500 [31:41<18:20,  6.05s/it]

[I 2026-10-05 15:24:48,284] Trial 447 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014368292600262192, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  64%|██████▍   | 319/500 [31:47<18:02,  5.98s/it]

[I 2026-10-05 15:24:54,099] Trial 448 finished with value: 0.8271604938271606 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0023443963068301476, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  64%|██████▍   | 320/500 [31:53<17:36,  5.87s/it]

[I 2026-10-05 15:24:59,722] Trial 449 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0022487846475626625, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  64%|██████▍   | 321/500 [31:56<15:02,  5.04s/it]

[I 2026-10-05 15:25:02,826] Trial 450 finished with value: 0.7373737373737373 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.002325719640063852, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  64%|██████▍   | 322/500 [32:02<16:26,  5.54s/it]

[I 2026-10-05 15:25:09,542] Trial 451 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015845409952390409, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  65%|██████▍   | 323/500 [32:09<16:56,  5.75s/it]

[I 2026-10-05 15:25:15,756] Trial 452 finished with value: 0.8103254769921436 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017615520669929823, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  65%|██████▍   | 324/500 [32:16<17:50,  6.08s/it]

[I 2026-10-05 15:25:22,621] Trial 453 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012979534149514943, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  65%|██████▌   | 325/500 [32:20<16:12,  5.56s/it]

[I 2026-10-05 15:25:26,955] Trial 454 finished with value: 0.8024691358024691 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0013592608606563092, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  65%|██████▌   | 326/500 [32:26<16:22,  5.65s/it]

[I 2026-10-05 15:25:32,800] Trial 455 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0024294656806138825, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  65%|██████▌   | 327/500 [32:31<15:54,  5.52s/it]

[I 2026-10-05 15:25:38,036] Trial 456 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0014938678181121907, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  66%|██████▌   | 328/500 [32:37<16:36,  5.79s/it]

[I 2026-10-05 15:25:44,474] Trial 457 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015172283102776359, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  66%|██████▌   | 329/500 [32:47<19:58,  7.01s/it]

[I 2026-10-05 15:25:54,318] Trial 458 finished with value: 0.8215488215488217 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013833586504750917, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 5, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  66%|██████▌   | 330/500 [32:52<17:49,  6.29s/it]

[I 2026-10-05 15:25:58,937] Trial 459 finished with value: 0.8024691358024691 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0018043658174190927, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  66%|██████▌   | 331/500 [32:58<17:20,  6.16s/it]

[I 2026-10-05 15:26:04,780] Trial 460 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0013054194784569175, 'weight_decay': 1e-07, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  66%|██████▋   | 332/500 [33:02<15:52,  5.67s/it]

[I 2026-10-05 15:26:09,315] Trial 461 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002097520023114308, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  67%|██████▋   | 333/500 [33:07<14:58,  5.38s/it]

[I 2026-10-05 15:26:14,009] Trial 462 finished with value: 0.8181818181818182 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018444763997499199, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  67%|██████▋   | 334/500 [33:15<16:53,  6.11s/it]

[I 2026-10-05 15:26:21,823] Trial 463 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013362985921671637, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  67%|██████▋   | 335/500 [33:20<15:59,  5.82s/it]

[I 2026-10-05 15:26:26,958] Trial 464 finished with value: 0.8148148148148148 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.00141412130462536, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  67%|██████▋   | 336/500 [33:26<15:45,  5.77s/it]

[I 2026-10-05 15:26:32,608] Trial 465 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.002108583438422889, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  67%|██████▋   | 337/500 [33:30<14:20,  5.28s/it]

[I 2026-10-05 15:26:36,760] Trial 466 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002319004503774969, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  68%|██████▊   | 338/500 [33:37<15:31,  5.75s/it]

[I 2026-10-05 15:26:43,582] Trial 467 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001418795835436803, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  68%|██████▊   | 339/500 [33:43<16:01,  5.97s/it]

[I 2026-10-05 15:26:50,081] Trial 468 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013306279417269725, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  68%|██████▊   | 340/500 [33:47<14:07,  5.30s/it]

[I 2026-10-05 15:26:53,802] Trial 469 finished with value: 0.8170594837261503 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012534100262488728, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  68%|██████▊   | 341/500 [33:54<15:20,  5.79s/it]

[I 2026-10-05 15:27:00,743] Trial 470 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001343364368020453, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  68%|██████▊   | 342/500 [33:59<15:04,  5.73s/it]

[I 2026-10-05 15:27:06,325] Trial 471 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001642132256068197, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  69%|██████▊   | 343/500 [34:06<16:06,  6.16s/it]

[I 2026-10-05 15:27:13,481] Trial 472 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001683493881866004, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  69%|██████▉   | 344/500 [34:13<16:37,  6.39s/it]

[I 2026-10-05 15:27:20,422] Trial 473 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.00128650944727664, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  69%|██████▉   | 345/500 [34:17<14:08,  5.47s/it]

[I 2026-10-05 15:27:23,753] Trial 474 finished with value: 0.8159371492704826 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013216142688467255, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  69%|██████▉   | 346/500 [34:22<14:19,  5.58s/it]

[I 2026-10-05 15:27:29,593] Trial 475 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0021078877903096998, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  69%|██████▉   | 347/500 [34:26<12:52,  5.05s/it]

[I 2026-10-05 15:27:33,392] Trial 476 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017592416037674743, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  70%|██████▉   | 348/500 [34:32<13:16,  5.24s/it]

[I 2026-10-05 15:27:39,081] Trial 477 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013207414872675283, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  70%|██████▉   | 349/500 [34:39<14:40,  5.83s/it]

[I 2026-10-05 15:27:46,293] Trial 478 finished with value: 0.745230078563412 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0013021670662481711, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  70%|███████   | 350/500 [34:46<15:10,  6.07s/it]

[I 2026-10-05 15:27:52,927] Trial 479 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012875080828145622, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  70%|███████   | 351/500 [34:52<15:22,  6.19s/it]

[I 2026-10-05 15:27:59,384] Trial 480 finished with value: 0.7508417508417509 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0013277198458973962, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  70%|███████   | 352/500 [34:57<13:48,  5.60s/it]

[I 2026-10-05 15:28:03,608] Trial 481 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0024687864170051988, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  71%|███████   | 353/500 [35:02<13:51,  5.65s/it]

[I 2026-10-05 15:28:09,391] Trial 482 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001644577104232588, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  71%|███████   | 354/500 [35:08<13:43,  5.64s/it]

[I 2026-10-05 15:28:15,008] Trial 483 finished with value: 0.8148148148148149 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0019972264655442663, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  71%|███████   | 355/500 [35:14<13:57,  5.77s/it]

[I 2026-10-05 15:28:21,092] Trial 484 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0012322778555438334, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  71%|███████   | 356/500 [35:16<11:29,  4.79s/it]

[I 2026-10-05 15:28:23,575] Trial 485 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.002007886595938223, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  71%|███████▏  | 357/500 [35:30<17:20,  7.28s/it]

[I 2026-10-05 15:28:36,652] Trial 486 finished with value: 0.8148148148148149 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0014040914955388748, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 5, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  72%|███████▏  | 358/500 [35:37<17:11,  7.27s/it]

[I 2026-10-05 15:28:43,900] Trial 487 finished with value: 0.8193041526374859 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0012214682641930653, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  72%|███████▏  | 359/500 [35:40<13:55,  5.92s/it]

[I 2026-10-05 15:28:46,683] Trial 488 finished with value: 0.8170594837261503 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002031573931012742, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  72%|███████▏  | 360/500 [35:46<13:59,  6.00s/it]

[I 2026-10-05 15:28:52,861] Trial 489 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015833475547054599, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  72%|███████▏  | 361/500 [35:52<14:12,  6.13s/it]

[I 2026-10-05 15:28:59,309] Trial 490 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014400117496547714, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  72%|███████▏  | 362/500 [35:56<12:42,  5.52s/it]

[I 2026-10-05 15:29:03,416] Trial 491 finished with value: 0.8114478114478114 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.00131136980647025, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  73%|███████▎  | 363/500 [36:04<13:51,  6.07s/it]

[I 2026-10-05 15:29:10,758] Trial 492 finished with value: 0.8159371492704827 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0014294787110895899, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  73%|███████▎  | 364/500 [36:11<14:41,  6.48s/it]

[I 2026-10-05 15:29:18,188] Trial 493 finished with value: 0.8148148148148149 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001223647461139598, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  73%|███████▎  | 365/500 [36:18<14:35,  6.49s/it]

[I 2026-10-05 15:29:24,693] Trial 494 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014862630215852135, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  73%|███████▎  | 366/500 [36:24<14:30,  6.49s/it]

[I 2026-10-05 15:29:31,207] Trial 495 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001630264846613976, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  73%|███████▎  | 367/500 [36:31<14:23,  6.49s/it]

[I 2026-10-05 15:29:37,684] Trial 496 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0012463734509091046, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  74%|███████▎  | 368/500 [36:38<14:50,  6.75s/it]

[I 2026-10-05 15:29:45,028] Trial 497 finished with value: 0.8193041526374859 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.002013610395791459, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  74%|███████▍  | 369/500 [36:44<14:01,  6.42s/it]

[I 2026-10-05 15:29:50,686] Trial 498 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013081638231508563, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  74%|███████▍  | 370/500 [36:50<13:51,  6.39s/it]

[I 2026-10-05 15:29:57,020] Trial 499 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001224341433924321, 'weight_decay': 1e-07, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  74%|███████▍  | 371/500 [36:56<13:20,  6.20s/it]

[I 2026-10-05 15:30:02,785] Trial 500 finished with value: 0.8260381593714926 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0015490141601647214, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  74%|███████▍  | 372/500 [37:02<13:27,  6.31s/it]

[I 2026-10-05 15:30:09,333] Trial 501 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001697357334537921, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  75%|███████▍  | 373/500 [37:08<13:02,  6.16s/it]

[I 2026-10-05 15:30:15,140] Trial 502 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013910123581114624, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  75%|███████▍  | 374/500 [37:12<11:47,  5.61s/it]

[I 2026-10-05 15:30:19,489] Trial 503 finished with value: 0.8136924803591471 and parameters: {'activation': 'silu', 'batch_size': 64, 'learning_rate': 0.0016436807603914397, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  75%|███████▌  | 375/500 [37:20<12:38,  6.07s/it]

[I 2026-10-05 15:30:26,614] Trial 504 finished with value: 0.8193041526374859 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001993272025301617, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  75%|███████▌  | 376/500 [37:34<17:58,  8.70s/it]

[I 2026-10-05 15:30:41,449] Trial 505 finished with value: 0.8181818181818182 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013648836570464644, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 5, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  75%|███████▌  | 377/500 [37:41<16:33,  8.07s/it]

[I 2026-10-05 15:30:48,067] Trial 506 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015756630925544614, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  76%|███████▌  | 378/500 [37:46<14:28,  7.12s/it]

[I 2026-10-05 15:30:52,968] Trial 507 finished with value: 0.8125701459034792 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012451961874020102, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  76%|███████▌  | 379/500 [37:51<13:18,  6.60s/it]

[I 2026-10-05 15:30:58,349] Trial 508 finished with value: 0.7485970819304152 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.001222805506034687, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  76%|███████▌  | 380/500 [37:58<13:35,  6.79s/it]

[I 2026-10-05 15:31:05,593] Trial 509 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014922847669601067, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  76%|███████▌  | 381/500 [38:02<11:25,  5.76s/it]

[I 2026-10-05 15:31:08,943] Trial 510 finished with value: 0.8148148148148149 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001324902775450903, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  76%|███████▋  | 382/500 [38:08<11:32,  5.87s/it]

[I 2026-10-05 15:31:15,069] Trial 511 finished with value: 0.8148148148148149 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001220423022287248, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  77%|███████▋  | 383/500 [38:14<11:39,  5.98s/it]

[I 2026-10-05 15:31:21,307] Trial 512 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.00128399079627595, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  77%|███████▋  | 384/500 [38:21<11:49,  6.12s/it]

[I 2026-10-05 15:31:27,753] Trial 513 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013640411004652896, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  77%|███████▋  | 385/500 [38:27<11:46,  6.14s/it]

[I 2026-10-05 15:31:33,950] Trial 514 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017491522394975294, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  77%|███████▋  | 386/500 [38:33<11:53,  6.26s/it]

[I 2026-10-05 15:31:40,491] Trial 515 finished with value: 0.7508417508417509 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0012582481350598058, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  77%|███████▋  | 387/500 [38:36<09:45,  5.18s/it]

[I 2026-10-05 15:31:43,138] Trial 516 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014906927451098658, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  78%|███████▊  | 388/500 [38:42<10:02,  5.38s/it]

[I 2026-10-05 15:31:48,975] Trial 517 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018009049857897284, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  78%|███████▊  | 389/500 [38:56<15:03,  8.14s/it]

[I 2026-10-05 15:32:03,566] Trial 518 finished with value: 0.8159371492704827 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014320679125276496, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 5, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  78%|███████▊  | 390/500 [39:03<13:59,  7.64s/it]

[I 2026-10-05 15:32:10,026] Trial 519 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015970487062483291, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  78%|███████▊  | 391/500 [39:09<12:44,  7.02s/it]

[I 2026-10-05 15:32:15,595] Trial 520 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0021533186417829666, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  78%|███████▊  | 392/500 [39:15<12:28,  6.93s/it]

[I 2026-10-05 15:32:22,336] Trial 521 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001682644001327814, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  79%|███████▊  | 393/500 [39:22<12:08,  6.81s/it]

[I 2026-10-05 15:32:28,846] Trial 522 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015926615225349426, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  79%|███████▉  | 394/500 [39:27<11:25,  6.47s/it]

[I 2026-10-05 15:32:34,522] Trial 523 finished with value: 0.8249158249158248 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016174789854724845, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  79%|███████▉  | 395/500 [39:36<12:29,  7.14s/it]

[I 2026-10-05 15:32:43,219] Trial 524 finished with value: 0.8181818181818182 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013140576746692697, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  79%|███████▉  | 396/500 [39:41<11:08,  6.43s/it]

[I 2026-10-05 15:32:48,006] Trial 525 finished with value: 0.8148148148148149 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0016712420024060813, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 5, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  79%|███████▉  | 397/500 [39:47<10:46,  6.27s/it]

[I 2026-10-05 15:32:53,912] Trial 526 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013891481431559593, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  80%|███████▉  | 398/500 [39:51<09:35,  5.64s/it]

[I 2026-10-05 15:32:58,069] Trial 527 finished with value: 0.8181818181818182 and parameters: {'activation': 'gelu', 'batch_size': 64, 'learning_rate': 0.00219968065349655, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  80%|███████▉  | 399/500 [39:56<09:12,  5.47s/it]

[I 2026-10-05 15:33:03,160] Trial 528 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0018089452071535386, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  80%|████████  | 400/500 [40:00<08:12,  4.92s/it]

[I 2026-10-05 15:33:06,786] Trial 529 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012579905261054963, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  80%|████████  | 401/500 [40:06<09:01,  5.47s/it]

[I 2026-10-05 15:33:13,549] Trial 530 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013181456804933964, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  80%|████████  | 402/500 [40:13<09:27,  5.79s/it]

[I 2026-10-05 15:33:20,078] Trial 531 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014541084694787484, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  81%|████████  | 403/500 [40:16<07:59,  4.94s/it]

[I 2026-10-05 15:33:23,037] Trial 532 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001350309846826212, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  81%|████████  | 404/500 [40:22<08:21,  5.22s/it]

[I 2026-10-05 15:33:28,917] Trial 533 finished with value: 0.8204264870931538 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.002302386877945679, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  81%|████████  | 405/500 [40:28<08:32,  5.40s/it]

[I 2026-10-05 15:33:34,725] Trial 534 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0020369649784039274, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  81%|████████  | 406/500 [40:33<08:28,  5.41s/it]

[I 2026-10-05 15:33:40,179] Trial 535 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.002429627874477434, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  81%|████████▏ | 407/500 [40:37<07:53,  5.09s/it]

[I 2026-10-05 15:33:44,523] Trial 536 finished with value: 0.819304152637486 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017926350955644542, 'weight_decay': 0.0001, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  82%|████████▏ | 408/500 [40:44<08:17,  5.40s/it]

[I 2026-10-05 15:33:50,653] Trial 537 finished with value: 0.8282828282828283 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0016812761892846468, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  82%|████████▏ | 409/500 [40:49<08:09,  5.38s/it]

[I 2026-10-05 15:33:55,979] Trial 538 finished with value: 0.7564534231200898 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.001335896534125887, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  82%|████████▏ | 410/500 [40:52<06:53,  4.59s/it]

[I 2026-10-05 15:33:58,737] Trial 539 finished with value: 0.8193041526374859 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0022212331249221624, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  82%|████████▏ | 411/500 [41:01<08:45,  5.91s/it]

[I 2026-10-05 15:34:07,711] Trial 540 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0012756345187936568, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  82%|████████▏ | 412/500 [41:08<09:08,  6.23s/it]

[I 2026-10-05 15:34:14,679] Trial 541 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0016856122306842822, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  83%|████████▎ | 413/500 [41:13<08:50,  6.10s/it]

[I 2026-10-05 15:34:20,494] Trial 542 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015479437989959555, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  83%|████████▎ | 414/500 [41:16<07:21,  5.13s/it]

[I 2026-10-05 15:34:23,357] Trial 543 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002372777057452314, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  83%|████████▎ | 415/500 [41:22<07:25,  5.24s/it]

[I 2026-10-05 15:34:28,858] Trial 544 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0016334734822850514, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  83%|████████▎ | 416/500 [41:27<07:32,  5.39s/it]

[I 2026-10-05 15:34:34,584] Trial 545 finished with value: 0.8249158249158248 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0015674862262478086, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  83%|████████▎ | 417/500 [41:34<07:59,  5.77s/it]

[I 2026-10-05 15:34:41,261] Trial 546 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014622157299914746, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  84%|████████▎ | 418/500 [41:37<06:38,  4.86s/it]

[I 2026-10-05 15:34:43,980] Trial 547 finished with value: 0.8204264870931537 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017955560466558606, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  84%|████████▍ | 419/500 [41:43<07:08,  5.29s/it]

[I 2026-10-05 15:34:50,295] Trial 548 finished with value: 0.819304152637486 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001259832010589801, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  84%|████████▍ | 420/500 [41:46<06:05,  4.57s/it]

[I 2026-10-05 15:34:53,178] Trial 549 finished with value: 0.8159371492704827 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013831258489289415, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  84%|████████▍ | 421/500 [41:50<05:44,  4.36s/it]

[I 2026-10-05 15:34:57,054] Trial 550 finished with value: 0.8035914702581369 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0017848356087513506, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  84%|████████▍ | 422/500 [41:58<06:55,  5.33s/it]

[I 2026-10-05 15:35:04,639] Trial 551 finished with value: 0.8125701459034792 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001385652617487852, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  85%|████████▍ | 423/500 [42:06<08:04,  6.29s/it]

[I 2026-10-05 15:35:13,161] Trial 552 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001257677785427288, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  85%|████████▍ | 424/500 [42:10<07:10,  5.66s/it]

[I 2026-10-05 15:35:17,360] Trial 553 finished with value: 0.8136924803591471 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0017097243170856725, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  85%|████████▌ | 425/500 [42:16<07:04,  5.66s/it]

[I 2026-10-05 15:35:23,007] Trial 554 finished with value: 0.8170594837261503 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0013269287859427454, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  85%|████████▌ | 426/500 [42:20<06:31,  5.29s/it]

[I 2026-10-05 15:35:27,423] Trial 555 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002286444392456541, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  85%|████████▌ | 427/500 [42:27<07:01,  5.78s/it]

[I 2026-10-05 15:35:34,343] Trial 556 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0012760987439697957, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  86%|████████▌ | 428/500 [42:34<07:15,  6.05s/it]

[I 2026-10-05 15:35:41,023] Trial 557 finished with value: 0.8170594837261503 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0012928324524733212, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  86%|████████▌ | 429/500 [42:40<06:59,  5.90s/it]

[I 2026-10-05 15:35:46,594] Trial 558 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0016577096037438976, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  86%|████████▌ | 430/500 [42:45<06:41,  5.73s/it]

[I 2026-10-05 15:35:51,922] Trial 559 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018406991149386225, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  86%|████████▌ | 431/500 [42:48<05:46,  5.02s/it]

[I 2026-10-05 15:35:55,266] Trial 560 finished with value: 0.818181818181818 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013722965535069402, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  86%|████████▋ | 432/500 [42:54<06:03,  5.35s/it]

[I 2026-10-05 15:36:01,384] Trial 561 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012592671265271279, 'weight_decay': 1e-07, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  87%|████████▋ | 433/500 [43:00<06:07,  5.49s/it]

[I 2026-10-05 15:36:07,203] Trial 562 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0016134944832050626, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  87%|████████▋ | 434/500 [43:06<06:13,  5.65s/it]

[I 2026-10-05 15:36:13,244] Trial 563 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0014208281453504503, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  87%|████████▋ | 435/500 [43:12<06:14,  5.75s/it]

[I 2026-10-05 15:36:19,234] Trial 564 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013948354014196996, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  87%|████████▋ | 436/500 [43:19<06:27,  6.05s/it]

[I 2026-10-05 15:36:25,989] Trial 565 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001309813787523479, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  87%|████████▋ | 437/500 [43:23<05:45,  5.48s/it]

[I 2026-10-05 15:36:30,140] Trial 566 finished with value: 0.8159371492704826 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013573013830380826, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  88%|████████▊ | 438/500 [43:30<06:11,  5.98s/it]

[I 2026-10-05 15:36:37,289] Trial 567 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013737752802344368, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  88%|████████▊ | 439/500 [43:35<05:38,  5.54s/it]

[I 2026-10-05 15:36:41,802] Trial 568 finished with value: 0.8181818181818182 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001831023800982574, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  88%|████████▊ | 440/500 [43:43<06:27,  6.46s/it]

[I 2026-10-05 15:36:50,391] Trial 569 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013833892927078665, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  88%|████████▊ | 441/500 [43:50<06:23,  6.50s/it]

[I 2026-10-05 15:36:56,979] Trial 570 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001362880107194051, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  88%|████████▊ | 442/500 [43:57<06:29,  6.72s/it]

[I 2026-10-05 15:37:04,227] Trial 571 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0012614393278463183, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  89%|████████▊ | 443/500 [44:03<06:16,  6.61s/it]

[I 2026-10-05 15:37:10,586] Trial 572 finished with value: 0.8271604938271605 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013849155031599334, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  89%|████████▉ | 444/500 [44:08<05:37,  6.04s/it]

[I 2026-10-05 15:37:15,276] Trial 573 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002065732149940479, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  89%|████████▉ | 445/500 [44:12<04:52,  5.32s/it]

[I 2026-10-05 15:37:18,923] Trial 574 finished with value: 0.8260381593714926 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0023455001477380214, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  89%|████████▉ | 446/500 [44:16<04:20,  4.83s/it]

[I 2026-10-05 15:37:22,610] Trial 575 finished with value: 0.8204264870931537 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001407727878535581, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.01}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  89%|████████▉ | 447/500 [44:31<07:01,  7.95s/it]

[I 2026-10-05 15:37:37,850] Trial 576 finished with value: 0.8159371492704826 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013193128490590217, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 5, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  90%|████████▉ | 448/500 [44:38<06:34,  7.59s/it]

[I 2026-10-05 15:37:44,604] Trial 577 finished with value: 0.8282828282828283 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012360161281287651, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  90%|████████▉ | 449/500 [44:40<05:16,  6.21s/it]

[I 2026-10-05 15:37:47,581] Trial 578 finished with value: 0.8047138047138048 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.002136510644895089, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  90%|█████████ | 450/500 [44:45<04:39,  5.58s/it]

[I 2026-10-05 15:37:51,697] Trial 579 finished with value: 0.8080808080808081 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013350510731988696, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  90%|█████████ | 451/500 [44:52<05:01,  6.16s/it]

[I 2026-10-05 15:37:59,210] Trial 580 finished with value: 0.8170594837261503 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.001252216934811078, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  90%|█████████ | 452/500 [44:59<05:02,  6.30s/it]

[I 2026-10-05 15:38:05,822] Trial 581 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0017643253483199113, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  91%|█████████ | 453/500 [45:05<04:49,  6.17s/it]

[I 2026-10-05 15:38:11,683] Trial 582 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017624468941484686, 'weight_decay': 1e-05, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  91%|█████████ | 454/500 [45:10<04:38,  6.05s/it]

[I 2026-10-05 15:38:17,469] Trial 583 finished with value: 0.8159371492704827 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.00134780660584167, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  91%|█████████ | 455/500 [45:16<04:29,  5.98s/it]

[I 2026-10-05 15:38:23,290] Trial 584 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0021580855854663244, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  91%|█████████ | 456/500 [45:23<04:28,  6.09s/it]

[I 2026-10-05 15:38:29,640] Trial 585 finished with value: 0.8249158249158249 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012669769549584627, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  91%|█████████▏| 457/500 [45:31<04:53,  6.83s/it]

[I 2026-10-05 15:38:38,183] Trial 586 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001291139929035751, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  92%|█████████▏| 458/500 [45:34<04:02,  5.77s/it]

[I 2026-10-05 15:38:41,480] Trial 587 finished with value: 0.819304152637486 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001245953734075196, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  92%|█████████▏| 459/500 [45:39<03:43,  5.46s/it]

[I 2026-10-05 15:38:46,226] Trial 588 finished with value: 0.8215488215488215 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0013260668744693022, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  92%|█████████▏| 460/500 [45:42<03:11,  4.78s/it]

[I 2026-10-05 15:38:49,432] Trial 589 finished with value: 0.8080808080808081 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0013834197802334058, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  92%|█████████▏| 461/500 [45:46<02:52,  4.42s/it]

[I 2026-10-05 15:38:53,006] Trial 590 finished with value: 0.8159371492704826 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017642543065679132, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  92%|█████████▏| 462/500 [45:52<03:03,  4.83s/it]

[I 2026-10-05 15:38:58,797] Trial 591 finished with value: 0.8249158249158249 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018307279413975982, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  93%|█████████▎| 463/500 [45:56<02:51,  4.63s/it]

[I 2026-10-05 15:39:02,955] Trial 592 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014397063453964176, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  93%|█████████▎| 464/500 [46:01<02:47,  4.67s/it]

[I 2026-10-05 15:39:07,701] Trial 593 finished with value: 0.8204264870931537 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012809438818398447, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  93%|█████████▎| 465/500 [46:08<03:16,  5.63s/it]

[I 2026-10-05 15:39:15,573] Trial 594 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014624235369297823, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  93%|█████████▎| 466/500 [46:13<02:55,  5.17s/it]

[I 2026-10-05 15:39:19,684] Trial 595 finished with value: 0.8215488215488215 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018265525231241297, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  93%|█████████▎| 467/500 [46:19<02:59,  5.43s/it]

[I 2026-10-05 15:39:25,729] Trial 596 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001323088534882104, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  94%|█████████▎| 468/500 [46:26<03:11,  5.98s/it]

[I 2026-10-05 15:39:32,988] Trial 597 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0013076472730580231, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  94%|█████████▍| 469/500 [46:31<02:55,  5.66s/it]

[I 2026-10-05 15:39:37,894] Trial 598 finished with value: 0.8069584736251403 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.001265679915001269, 'weight_decay': 1e-05, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  94%|█████████▍| 470/500 [46:35<02:36,  5.23s/it]

[I 2026-10-05 15:39:42,133] Trial 599 finished with value: 0.8125701459034792 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001340531266658266, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 12}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  94%|█████████▍| 471/500 [46:40<02:33,  5.28s/it]

[I 2026-10-05 15:39:47,512] Trial 600 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0013570977412623684, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  94%|█████████▍| 472/500 [46:45<02:19,  4.99s/it]

[I 2026-10-05 15:39:51,842] Trial 601 finished with value: 0.8024691358024691 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0016798089766668816, 'weight_decay': 1e-06, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  95%|█████████▍| 473/500 [46:49<02:10,  4.82s/it]

[I 2026-10-05 15:39:56,266] Trial 602 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.001687278035798554, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  95%|█████████▍| 474/500 [46:55<02:15,  5.22s/it]

[I 2026-10-05 15:40:02,410] Trial 603 finished with value: 0.8260381593714926 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0016345729728113017, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  95%|█████████▌| 475/500 [47:02<02:24,  5.77s/it]

[I 2026-10-05 15:40:09,468] Trial 604 finished with value: 0.8260381593714928 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0014869048103758218, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  95%|█████████▌| 476/500 [47:08<02:20,  5.83s/it]

[I 2026-10-05 15:40:15,454] Trial 605 finished with value: 0.8148148148148149 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.0013659621332357261, 'weight_decay': 1e-06, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  95%|█████████▌| 477/500 [47:16<02:25,  6.34s/it]

[I 2026-10-05 15:40:22,986] Trial 606 finished with value: 0.8159371492704827 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0012680974509987866, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  96%|█████████▌| 478/500 [47:19<01:57,  5.32s/it]

[I 2026-10-05 15:40:25,926] Trial 607 finished with value: 0.8215488215488215 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.001926623271782181, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  96%|█████████▌| 479/500 [47:23<01:41,  4.83s/it]

[I 2026-10-05 15:40:29,615] Trial 608 finished with value: 0.7485970819304152 and parameters: {'activation': 'squared_relu', 'batch_size': 64, 'learning_rate': 0.001960580384266812, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  96%|█████████▌| 480/500 [47:33<02:09,  6.45s/it]

[I 2026-10-05 15:40:39,844] Trial 609 finished with value: 0.8136924803591471 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0014204857408586058, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  96%|█████████▌| 481/500 [47:37<01:48,  5.71s/it]

[I 2026-10-05 15:40:43,836] Trial 610 finished with value: 0.8136924803591471 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0021130601554659057, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  96%|█████████▋| 482/500 [47:43<01:45,  5.84s/it]

[I 2026-10-05 15:40:49,972] Trial 611 finished with value: 0.8170594837261503 and parameters: {'activation': 'silu', 'batch_size': 32, 'learning_rate': 0.0012490494102884307, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  97%|█████████▋| 483/500 [47:47<01:29,  5.27s/it]

[I 2026-10-05 15:40:53,918] Trial 612 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 64, 'learning_rate': 0.002125911662636691, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  97%|█████████▋| 484/500 [47:54<01:32,  5.75s/it]

[I 2026-10-05 15:41:00,786] Trial 613 finished with value: 0.8260381593714928 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012468618669883795, 'weight_decay': 1e-06, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  97%|█████████▋| 485/500 [47:57<01:16,  5.12s/it]

[I 2026-10-05 15:41:04,428] Trial 614 finished with value: 0.8148148148148149 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012765393340197675, 'weight_decay': 1e-07, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  97%|█████████▋| 486/500 [48:02<01:08,  4.90s/it]

[I 2026-10-05 15:41:08,818] Trial 615 finished with value: 0.7396184062850729 and parameters: {'activation': 'squared_relu', 'batch_size': 64, 'learning_rate': 0.0018856132284616354, 'weight_decay': 1e-06, 'dropout': 0.3, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  97%|█████████▋| 487/500 [48:07<01:04,  4.95s/it]

[I 2026-10-05 15:41:13,890] Trial 616 finished with value: 0.8148148148148148 and parameters: {'activation': 'silu', 'batch_size': 64, 'learning_rate': 0.001305353202850942, 'weight_decay': 1e-05, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  98%|█████████▊| 488/500 [48:12<01:00,  5.08s/it]

[I 2026-10-05 15:41:19,275] Trial 617 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013489149423957531, 'weight_decay': 1e-05, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  98%|█████████▊| 489/500 [48:15<00:49,  4.46s/it]

[I 2026-10-05 15:41:22,289] Trial 618 finished with value: 0.8226711560044894 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013021864651414812, 'weight_decay': 0.0001, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 16, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  98%|█████████▊| 490/500 [48:27<01:06,  6.61s/it]

[I 2026-10-05 15:41:33,903] Trial 619 finished with value: 0.8103254769921436 and parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0013903498894180049, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 4, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  98%|█████████▊| 491/500 [48:30<00:50,  5.59s/it]

[I 2026-10-05 15:41:37,132] Trial 620 finished with value: 0.809203142536476 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.0012226331835707694, 'weight_decay': 0.0001, 'dropout': 0.05, 'n_layers': 3, 'hidden_dim': 16}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  98%|█████████▊| 492/500 [48:34<00:41,  5.13s/it]

[I 2026-10-05 15:41:41,174] Trial 621 finished with value: 0.8226711560044894 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0016571894809145275, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 8}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  99%|█████████▊| 493/500 [48:40<00:37,  5.40s/it]

[I 2026-10-05 15:41:47,206] Trial 622 finished with value: 0.8226711560044894 and parameters: {'activation': 'gelu', 'batch_size': 32, 'learning_rate': 0.0013104137212616965, 'weight_decay': 0.0001, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  99%|█████████▉| 494/500 [48:46<00:33,  5.52s/it]

[I 2026-10-05 15:41:52,995] Trial 623 finished with value: 0.8271604938271605 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.002179011887440304, 'weight_decay': 1e-05, 'dropout': 0.2, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  99%|█████████▉| 495/500 [48:50<00:25,  5.02s/it]

[I 2026-10-05 15:41:56,868] Trial 624 finished with value: 0.8237934904601572 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0012588972418001612, 'weight_decay': 1e-07, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 8, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  99%|█████████▉| 496/500 [48:55<00:20,  5.05s/it]

[I 2026-10-05 15:42:01,986] Trial 625 finished with value: 0.7530864197530865 and parameters: {'activation': 'squared_relu', 'batch_size': 32, 'learning_rate': 0.00128717507091881, 'weight_decay': 1e-07, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772:  99%|█████████▉| 497/500 [49:01<00:16,  5.37s/it]

[I 2026-10-05 15:42:08,086] Trial 626 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0018360432876722412, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772: 100%|█████████▉| 498/500 [49:07<00:11,  5.51s/it]

[I 2026-10-05 15:42:13,944] Trial 627 finished with value: 0.8271604938271606 and parameters: {'activation': 'leaky_relu', 'batch_size': 32, 'learning_rate': 0.0013554407844808898, 'weight_decay': 1e-05, 'dropout': 0.25, 'n_layers': 3, 'hidden_dim': 4, 'negative_slope': 0.05}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772: 100%|█████████▉| 499/500 [49:14<00:06,  6.09s/it]

[I 2026-10-05 15:42:21,397] Trial 628 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0012007313769975244, 'weight_decay': 1e-06, 'dropout': 0.15000000000000002, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

Best trial: 0. Best value: 0.832772: 100%|██████████| 500/500 [49:20<00:00,  5.92s/it]

[I 2026-10-05 15:42:26,859] Trial 629 finished with value: 0.8237934904601572 and parameters: {'activation': 'relu', 'batch_size': 64, 'learning_rate': 0.0020405718123590036, 'weight_decay': 1e-06, 'dropout': 0.1, 'n_layers': 3, 'hidden_dim': 4}. Best is trial 0 with value: 0.8327721661054994.

## 5. Таблица результатов

`value` — средняя accuracy на трёх screening folds. Сохраняем таблицу в CSV,
чтобы результаты не зависели от состояния notebook.

In [8]:
trials = study.trials_dataframe()
csv_path = STUDY_DIR / f"{STUDY_NAME}_trials.csv"
trials.to_csv(csv_path, index=False)

columns = [
    "number", "value", "state",
    "params_activation", "params_negative_slope",
    "params_batch_size", "params_learning_rate", "params_weight_decay",
    "params_dropout", "params_n_layers", "params_hidden_dim",
    "user_attrs_accuracy_std", "user_attrs_log_loss_mean",
]
available = [column for column in columns if column in trials]
complete = trials.loc[trials["state"].eq("COMPLETE"), available]
display(complete.sort_values("value", ascending=False).head(15))

print("Saved:", csv_path.relative_to(PROJECT_ROOT))
print("Best screening accuracy:", study.best_value)
print("Best parameters:", study.best_params)

,number,value,state,params_activation,params_negative_slope,params_batch_size,params_learning_rate,params_weight_decay,params_dropout,params_n_layers,params_hidden_dim,user_attrs_accuracy_std,user_attrs_log_loss_mean
0,0,0.832772,COMPLETE,relu,NaN,32,0.001750,1.000000e-04,0.3,4,8,0.023888,0.454552
443,443,0.830527,COMPLETE,leaky_relu,0.05,32,0.002466,1.000000e-04,0.1,3,4,0.031285,0.423690
137,137,0.830527,COMPLETE,leaky_relu,0.05,32,0.001285,1.000000e-07,0.1,3,4,0.028036,0.422700
193,193,0.830527,COMPLETE,leaky_relu,0.05,32,0.001367,1.000000e-04,0.1,3,4,0.028036,0.422808
201,201,0.830527,COMPLETE,leaky_relu,0.05,32,0.001367,1.000000e-04,0.1,3,4,0.028036,0.422806
256,256,0.830527,COMPLETE,leaky_relu,0.05,32,0.001336,1.000000e-05,0.1,3,4,0.028036,0.422081
284,284,0.830527,COMPLETE,leaky_relu,0.05,32,0.001313,1.000000e-05,0.1,3,4,0.028036,0.422366
414,414,0.830527,COMPLETE,leaky_relu,0.05,32,0.001294,1.000000e-07,0.1,3,4,0.028036,0.422340
272,272,0.830527,COMPLETE,leaky_relu,0.05,32,0.001325,1.000000e-05,0.1,3,4,0.028036,0.422021
209,209,0.829405,COMPLETE,relu,NaN,32,0.001361,1.000000e-04,0.1,3,4,0.026153,0.423262
93,93,0.829405,COMPLETE,leaky_relu,0.05,32,0.001241,1.000000e-07,0.2,3,4,0.023888,0.424758
285,285,0.829405,COMPLETE,leaky_relu,0.05,32,0.001296,1.000000e-05,0.1,3,4,0.026153,0.422305
431,431,0.829405,COMPLETE,leaky_relu,0.05,32,0.001300,1.000000e-04,0.1,3,4,0.026153,0.422985
273,273,0.829405,COMPLETE,leaky_relu,0.05,32,0.001296,1.000000e-05,0.1,3,4,0.026153,0.422150
263,263,0.829405,COMPLETE,leaky_relu,0.05,32,0.001252,1.000000e-07,0.2,3,4,0.023888,0.423996

Saved: artifacts\optuna\titanic_mlp_tuning_002_trials.csv
Best screening accuracy: 0.8327721661054994
Best parameters: {'activation': 'relu', 'batch_size': 32, 'learning_rate': 0.0017503534730658975, 'weight_decay': 0.0001, 'dropout': 0.3, 'n_layers': 4, 'hidden_dim': 8}

## 6. Смотрим не только на одну лучшую trial

Одна trial может случайно удачно попасть в три folds. Здесь сравниваются число
попаданий каждой активации в top-20, её лучшая accuracy и медиана результатов.

In [9]:
complete_all = trials.loc[trials["state"].eq("COMPLETE")].copy()
top_20 = complete_all.nlargest(min(20, len(complete_all)), "value")

activation_summary = (
    complete_all.groupby("params_activation")
    .agg(
        trials=("number", "count"),
        best_accuracy=("value", "max"),
        median_accuracy=("value", "median"),
        mean_accuracy=("value", "mean"),
    )
    .sort_values("best_accuracy", ascending=False)
)
top_counts = top_20["params_activation"].value_counts().rename("top_20_count")
display(activation_summary.join(top_counts).fillna({"top_20_count": 0}))

,trials,best_accuracy,median_accuracy,mean_accuracy,top_20_count
params_activation,,,,,
relu,262,0.832772,0.822671,0.821335,5.0
leaky_relu,288,0.830527,0.823793,0.822617,15.0
gelu,31,0.824916,0.817059,0.815430,0.0
silu,26,0.822671,0.814815,0.815592,0.0
squared_relu,23,0.819304,0.750842,0.758210,0.0

## 7. Официальная перепроверка трёх лучших trials

Эта ячейка ничего не сохраняет в реестр и не принимает решение `adopt`. Она
заново обучает MLP-024 и три лучших кандидата на пяти folds с seed 42. Запускайте
её после окончания screening.

Если несколько лучших trials почти одинаковы, замените `head(3)` на выбранные
номера, чтобы проверить разные активации.

In [10]:
official_splits = tuning.make_stratified_splits(
    prepared,
    target=project_config.TARGET,
    n_splits=5,
    random_state=42,
)

reference_spec = replace(
    parent.EXPERIMENT,
    experiment_id="TUNE2-OFFICIAL-REFERENCE",
    title="MLP-024 official-fold reference",
    save_artifacts=False,
    sync_docs=False,
)
reference_result = mlp_tools.run_mlp_cv(
    prepared,
    target=project_config.TARGET,
    key=project_config.KEY,
    build_network=parent.build_network,
    spec=reference_spec,
    build_fold_transformer=build_fold_transformer,
    cv_splits=official_splits,
)

rows = [{
    "candidate": "MLP-024",
    "screening_trial": None,
    "accuracy": float(reference_result.summary.loc["accuracy", "mean"]),
    "accuracy_std": float(reference_result.summary.loc["accuracy", "std"]),
    "balanced_accuracy": float(reference_result.summary.loc["balanced_accuracy", "mean"]),
    "f1": float(reference_result.summary.loc["f1", "mean"]),
    "roc_auc": float(reference_result.summary.loc["roc_auc", "mean"]),
    "log_loss": float(reference_result.summary.loc["log_loss", "mean"]),
}]

selected_trials = sorted(
    (trial for trial in study.trials if trial.value is not None),
    key=lambda trial: trial.value,
    reverse=True,
)[:3]

for selected in selected_trials:
    parameters = selected.params
    candidate_spec = replace(
        parent.EXPERIMENT,
        experiment_id=f"TUNE2-OFFICIAL-{selected.number:04d}",
        title=f"Official-fold check of trial {selected.number}",
        training=tuning.training_from_parameters(parent.EXPERIMENT.training, parameters),
        save_artifacts=False,
        sync_docs=False,
    )
    result = mlp_tools.run_mlp_cv(
        prepared,
        target=project_config.TARGET,
        key=project_config.KEY,
        build_network=tuning.build_phase2_network_factory(parameters),
        spec=candidate_spec,
        build_fold_transformer=build_fold_transformer,
        cv_splits=official_splits,
    )
    rows.append({
        "candidate": f"trial {selected.number}: {parameters['activation']}",
        "screening_trial": selected.number,
        "accuracy": float(result.summary.loc["accuracy", "mean"]),
        "accuracy_std": float(result.summary.loc["accuracy", "std"]),
        "balanced_accuracy": float(result.summary.loc["balanced_accuracy", "mean"]),
        "f1": float(result.summary.loc["f1", "mean"]),
        "roc_auc": float(result.summary.loc["roc_auc", "mean"]),
        "log_loss": float(result.summary.loc["log_loss", "mean"]),
    })

official_comparison = pd.DataFrame(rows).sort_values("accuracy", ascending=False)
display(official_comparison)

,candidate,screening_trial,accuracy,accuracy_std,balanced_accuracy,f1,roc_auc,log_loss
0,MLP-024,NaN,0.838365,0.011105,0.817573,0.775582,0.878035,0.405802
2,trial 137: leaky_relu,137.0,0.823778,0.013175,0.801956,0.754702,0.874080,0.411377
3,trial 193: leaky_relu,193.0,0.823778,0.014323,0.800263,0.752603,0.874057,0.412888
1,trial 0: relu,0.0,0.819296,0.009417,0.799265,0.751380,0.871340,0.429972

## 8. Как принять решение

Победа на screening folds только выдвигает кандидата. Если он сохраняет улучшение
на пяти официальных folds, создайте обычный `new-MLPexperiment` на основе MLP-024,
перенесите выбранную архитектуру и выполните стандартный notebook. Только его
paired-сравнение и карточка используются для решения `adopt` или `reject`.

Не выбирайте seed как гиперпараметр: это поиск удачной случайности, а не модели.